import { EconomyData } from "./types";

// Curated economy data for major countries — can be replaced with live API
export const economyDatabase: Record<string, EconomyData> = {
  US: {
    gdp: "$25.5T",
    gdpPerCapita: "$76,330",
    currency: "USD ($)",
    inflation: "3.2%",
    unemployment: "3.7%",
    mainExports: ["Refined Petroleum", "Aircraft", "Medical Instruments", "Integrated Circuits"],
    stockIndex: "S&P 500",
    stockValue: "5,234",
    stockChange: "+1.2%",
  },
  CN: {
    gdp: "$17.9T",
    gdpPerCapita: "$12,720",
    currency: "CNY (¥)",
    inflation: "0.2%",
    unemployment: "5.2%",
    mainExports: ["Electronics", "Machinery", "Textiles", "Furniture"],
    stockIndex: "Shanghai Composite",
    stockValue: "3,088",
    stockChange: "-0.4%",
  },
  JP: {
    gdp: "$4.2T",
    gdpPerCapita: "$33,950",
    currency: "JPY (¥)",
    inflation: "2.8%",
    unemployment: "2.5%",
    mainExports: ["Vehicles", "Machinery", "Electronics", "Steel"],
    stockIndex: "Nikkei 225",
    stockValue: "39,740",
    stockChange: "+0.8%",
  },
  DE: {
    gdp: "$4.1T",
    gdpPerCapita: "$48,718",
    currency: "EUR (€)",
    inflation: "2.9%",
    unemployment: "5.7%",
    mainExports: ["Vehicles", "Machinery", "Chemical Products", "Electronics"],
    stockIndex: "DAX",
    stockValue: "18,200",
    stockChange: "+0.5%",
  },
  GB: {
    gdp: "$3.1T",
    gdpPerCapita: "$46,125",
    currency: "GBP (£)",
    inflation: "4.0%",
    unemployment: "4.2%",
    mainExports: ["Machinery", "Vehicles", "Pharmaceuticals", "Oil"],
    stockIndex: "FTSE 100",
    stockValue: "7,930",
    stockChange: "+0.3%",
  },
  IN: {
    gdp: "$3.7T",
    gdpPerCapita: "$2,612",
    currency: "INR (₹)",
    inflation: "5.1%",
    unemployment: "7.8%",
    mainExports: ["Refined Petroleum", "Diamonds", "Pharmaceuticals", "IT Services"],
    stockIndex: "SENSEX",
    stockValue: "73,500",
    stockChange: "+0.6%",
  },
  FR: {
    gdp: "$2.8T",
    gdpPerCapita: "$42,330",
    currency: "EUR (€)",
    inflation: "2.3%",
    unemployment: "7.4%",
    mainExports: ["Aircraft", "Vehicles", "Pharmaceuticals", "Wine"],
    stockIndex: "CAC 40",
    stockValue: "8,150",
    stockChange: "+0.4%",
  },
  BR: {
    gdp: "$2.1T",
    gdpPerCapita: "$9,673",
    currency: "BRL (R$)",
    inflation: "4.5%",
    unemployment: "7.6%",
    mainExports: ["Soybeans", "Iron Ore", "Crude Petroleum", "Sugar"],
    stockIndex: "IBOVESPA",
    stockValue: "128,400",
    stockChange: "-0.2%",
  },
  RU: {
    gdp: "$1.9T",
    gdpPerCapita: "$12,580",
    currency: "RUB (₽)",
    inflation: "7.4%",
    unemployment: "2.9%",
    mainExports: ["Crude Petroleum", "Natural Gas", "Metals", "Wheat"],
    stockIndex: "MOEX",
    stockValue: "3,280",
    stockChange: "-1.1%",
  },
  AU: {
    gdp: "$1.7T",
    gdpPerCapita: "$65,100",
    currency: "AUD (A$)",
    inflation: "3.4%",
    unemployment: "3.9%",
    mainExports: ["Iron Ore", "Coal", "Natural Gas", "Gold"],
    stockIndex: "ASX 200",
    stockValue: "7,840",
    stockChange: "+0.3%",
  },
  KR: {
    gdp: "$1.7T",
    gdpPerCapita: "$32,423",
    currency: "KRW (₩)",
    inflation: "3.6%",
    unemployment: "2.7%",
    mainExports: ["Semiconductors", "Vehicles", "Ships", "Displays"],
    stockIndex: "KOSPI",
    stockValue: "2,680",
    stockChange: "+0.7%",
  },
  SA: {
    gdp: "$1.1T",
    gdpPerCapita: "$30,436",
    currency: "SAR (﷼)",
    inflation: "1.6%",
    unemployment: "4.8%",
    mainExports: ["Crude Petroleum", "Refined Petroleum", "Polymers"],
    stockIndex: "Tadawul",
    stockValue: "12,150",
    stockChange: "+0.1%",
  },
  NG: {
    gdp: "$477B",
    gdpPerCapita: "$2,184",
    currency: "NGN (₦)",
    inflation: "28.9%",
    unemployment: "33.3%",
    mainExports: ["Crude Petroleum", "Natural Gas", "Cocoa"],
  },
  EG: {
    gdp: "$387B",
    gdpPerCapita: "$3,699",
    currency: "EGP (E£)",
    inflation: "35.7%",
    unemployment: "7.1%",
    mainExports: ["Petroleum Gas", "Crude Petroleum", "Fertilizers", "Textiles"],
  },
  IL: {
    gdp: "$525B",
    gdpPerCapita: "$55,535",
    currency: "ILS (₪)",
    inflation: "2.5%",
    unemployment: "3.4%",
    mainExports: ["Diamonds", "Electronics", "Pharmaceuticals", "Tech"],
    stockIndex: "TA-125",
    stockValue: "2,040",
    stockChange: "-0.8%",
  },
  UA: {
    gdp: "$160B",
    gdpPerCapita: "$4,530",
    currency: "UAH (₴)",
    inflation: "5.8%",
    unemployment: "18.0%",
    mainExports: ["Grain", "Iron", "Sunflower Oil", "Steel"],
  },
};
