/**
 * Famous landmarks / cities per country — shown as discovery chips
 * in the Overview tab. Covers the ~45 most-visited destinations.
 */
export const TOP_PLACES: Record<string, string[]> = {
  US: ["Statue of Liberty", "Grand Canyon", "Yellowstone", "Times Square", "Golden Gate Bridge", "Hollywood"],
  FR: ["Eiffel Tower", "Louvre Museum", "Mont Saint-Michel", "Palace of Versailles", "French Riviera", "Bordeaux"],
  IT: ["Colosseum", "Venice", "Amalfi Coast", "Florence Cathedral", "Pompeii", "Cinque Terre"],
  ES: ["Sagrada Família", "Alhambra", "Park Güell", "Seville", "Prado Museum", "Ibiza"],
  JP: ["Mount Fuji", "Kyoto", "Fushimi Inari", "Hiroshima Peace Park", "Osaka Castle", "Shibuya Crossing"],
  CN: ["Great Wall", "Forbidden City", "Li River", "Terracotta Army", "Yellow Mountains", "Shanghai Bund"],
  IN: ["Taj Mahal", "Varanasi Ghats", "Jaipur", "Goa Beaches", "Kerala Backwaters", "Mumbai"],
  BR: ["Christ the Redeemer", "Iguazú Falls", "Amazon Rainforest", "Copacabana Beach", "Pantanal", "Ouro Preto"],
  AU: ["Sydney Opera House", "Great Barrier Reef", "Uluru", "Bondi Beach", "Blue Mountains", "Melbourne"],
  DE: ["Brandenburg Gate", "Neuschwanstein Castle", "Cologne Cathedral", "Black Forest", "Berlin Wall Memorial", "Munich"],
  GB: ["Big Ben", "Stonehenge", "Edinburgh Castle", "Tower of London", "Lake District", "Oxford"],
  RU: ["Red Square", "Lake Baikal", "Trans-Siberian Railway", "Hermitage Museum", "St. Petersburg", "Kremlin"],
  CA: ["Niagara Falls", "Banff National Park", "CN Tower", "Vancouver", "Quebec City", "Northern Lights"],
  MX: ["Chichen Itza", "Teotihuacan", "Tulum", "Copper Canyon", "Oaxaca", "Mexico City"],
  GR: ["Acropolis", "Santorini", "Mykonos", "Delphi", "Meteora", "Rhodes"],
  EG: ["Pyramids of Giza", "Luxor Temple", "Abu Simbel", "Valley of the Kings", "Nile River", "Alexandria"],
  TR: ["Hagia Sophia", "Cappadocia", "Pamukkale", "Ephesus", "Topkapi Palace", "Göbekli Tepe"],
  TH: ["Wat Phra Kaew", "Chiang Mai", "Phuket", "Ayutthaya", "Phi Phi Islands", "Khao Yai"],
  ID: ["Bali", "Borobudur", "Komodo Island", "Lombok", "Yogyakarta", "Raja Ampat"],
  PE: ["Machu Picchu", "Cusco", "Lake Titicaca", "Nazca Lines", "Amazon Basin", "Colca Canyon"],
  AR: ["Buenos Aires", "Patagonia", "Iguazú Falls", "Mendoza", "Ushuaia", "Aconcagua"],
  ZA: ["Cape Town", "Kruger National Park", "Table Mountain", "Garden Route", "Johannesburg", "Robben Island"],
  KE: ["Maasai Mara", "Amboseli", "Diani Beach", "Nairobi National Park", "Lake Nakuru", "Mount Kenya"],
  MA: ["Marrakech", "Fez", "Chefchaouen", "Sahara Desert", "Casablanca", "Atlas Mountains"],
  NL: ["Amsterdam Canals", "Keukenhof", "Kinderdijk", "Rijksmuseum", "Van Gogh Museum", "Delft"],
  CH: ["Matterhorn", "Jungfraujoch", "Lucerne", "Lake Geneva", "Interlaken", "Zurich"],
  NO: ["Norwegian Fjords", "Northern Lights", "Bergen", "Geirangerfjord", "Lofoten Islands", "Trolltunga"],
  IS: ["Blue Lagoon", "Northern Lights", "Geysir", "Gullfoss", "Reykjavik", "Vatnajökull"],
  NZ: ["Milford Sound", "Hobbiton", "Queenstown", "Bay of Islands", "Tongariro", "Fiordland"],
  PT: ["Lisbon", "Porto", "Algarve", "Sintra", "Douro Valley", "Évora"],
  SE: ["Stockholm", "Gamla Stan", "Lapland", "Gothenburg", "Vasa Museum", "Abisko"],
  AT: ["Vienna", "Salzburg", "Hallstatt", "Schönbrunn Palace", "Innsbruck", "Tirol"],
  CZ: ["Prague Old Town", "Charles Bridge", "Český Krumlov", "Karlovy Vary", "Kutná Hora", "Prague Castle"],
  PL: ["Kraków", "Auschwitz Memorial", "Wieliczka Salt Mine", "Warsaw Old Town", "Gdańsk", "Zakopane"],
  AE: ["Burj Khalifa", "Palm Jumeirah", "Sheikh Zayed Mosque", "Dubai Mall", "Desert Safari", "Abu Dhabi"],
  SG: ["Marina Bay Sands", "Gardens by the Bay", "Sentosa Island", "Merlion Park", "Chinatown", "Orchard Road"],
  TW: ["Taipei 101", "Taroko Gorge", "Sun Moon Lake", "Jiufen", "Alishan", "Kenting"],
  VN: ["Ha Long Bay", "Hội An", "Phong Nha Caves", "Hue Citadel", "Hanoi Old Quarter", "Mỹ Sơn"],
  KH: ["Angkor Wat", "Bayon Temple", "Siem Reap", "Phnom Penh", "Tonle Sap Lake", "Koh Rong"],
  KR: ["Gyeongbokgung Palace", "Jeju Island", "Gyeongju", "Busan", "Seoraksan", "DMZ"],
  HU: ["Budapest Thermal Baths", "Parliament Building", "Fisherman's Bastion", "Lake Balaton", "Eger", "Tokaj"],
  RO: ["Transylvania", "Bran Castle", "Bucharest", "Danube Delta", "Painted Monasteries", "Sibiu"],
  HR: ["Dubrovnik Old City", "Plitvice Lakes", "Split", "Hvar Island", "Diocletian's Palace", "Rovinj"],
  TZ: ["Serengeti", "Zanzibar", "Kilimanjaro", "Ngorongoro Crater", "Stone Town", "Selous"],
  ET: ["Lalibela", "Axum", "Simien Mountains", "Danakil Depression", "Addis Ababa", "Omo Valley"],
  SA: ["Mecca", "Madinah", "AlUla", "Edge of the World", "Jeddah Historic District", "Diriyah"],
  IL: ["Jerusalem Old City", "Tel Aviv Beach", "Dead Sea", "Masada", "Haifa Bahá'í Gardens", "Sea of Galilee"],
  PH: ["Palawan", "Boracay", "Chocolate Hills", "Intramuros", "Banaue Rice Terraces", "Siargao"],
  MY: ["Petronas Towers", "Langkawi", "George Town", "Borneo Rainforest", "Cameron Highlands", "Batu Caves"],
  UA: ["Kyiv Pechersk Lavra", "Lviv Old Town", "Sophia Cathedral", "Carpathian Mountains", "Odesa", "Chernobyl"],
};

export function getTopPlaces(code: string): string[] {
  return TOP_PLACES[code] ?? [];
}
