// Travel & Culture data keyed by ISO alpha-2 country code
// Visa status is for Indian passport holders

export type VisaStatus = "free" | "on-arrival" | "e-visa" | "required";
export type SafetyLevel = "safe" | "caution" | "high-risk";

export interface KnownForItem {
  emoji: string;
  label: string;
}

// ─── Visa on arrival / e-visa / visa-free for Indian passport ────────────────
export const visaForIndian: Record<string, VisaStatus> = {
  IN: "free",
  US: "required",
  GB: "required",
  FR: "required",
  DE: "required",
  JP: "required",
  CN: "required",
  AU: "required",
  BR: "free",
  CA: "required",
  ZA: "required",
  AE: "on-arrival",
  SG: "required",
  TH: "on-arrival",
  IT: "required",
  ES: "required",
  MX: "free",
  ID: "free",
  NG: "on-arrival",
  EG: "on-arrival",
  KE: "e-visa",
  TR: "e-visa",
  SA: "e-visa",
  AR: "free",
  PL: "required",
  NL: "required",
  SE: "required",
  NO: "required",
  NZ: "e-visa",
  PT: "required",
  GR: "required",
  CH: "required",
  AT: "required",
  BE: "required",
  DK: "required",
  FI: "required",
  MY: "free",
  PH: "free",
  VN: "e-visa",
  LK: "e-visa",
  NP: "free",
  MV: "on-arrival",
  TW: "required",
  KR: "required",
  PE: "free",
  CO: "free",
  CL: "free",
  MA: "free",
  TN: "on-arrival",
  GH: "on-arrival",
  ET: "on-arrival",
  TZ: "on-arrival",
  UG: "on-arrival",
  QA: "on-arrival",
  KW: "required",
  BH: "on-arrival",
  OM: "on-arrival",
  JO: "on-arrival",
  IL: "required",
  RU: "required",
  UA: "free",
  CZ: "required",
  HU: "required",
  RO: "required",
  HR: "required",
  RS: "free",
  SK: "required",
  SI: "required",
  BG: "required",
  LT: "required",
  LV: "required",
  EE: "required",
  IS: "required",
  IE: "required",
  LU: "required",
};

// ─── Best time to visit ───────────────────────────────────────────────────────
export const bestTime: Record<string, string> = {
  IN: "Oct – Mar",
  US: "Apr – Jun",
  GB: "May – Sep",
  FR: "Apr – Oct",
  DE: "May – Sep",
  JP: "Mar – May",
  CN: "Apr – Jun",
  AU: "Sep – Nov",
  BR: "Apr – Jun",
  CA: "Jun – Aug",
  ZA: "May – Sep",
  AE: "Nov – Mar",
  SG: "Feb – Apr",
  TH: "Nov – Mar",
  IT: "Apr – Jun",
  ES: "Apr – Jun",
  MX: "Dec – Apr",
  ID: "Apr – Oct",
  NG: "Nov – Feb",
  EG: "Oct – Apr",
  KE: "Jul – Oct",
  TR: "Apr – Jun",
  SA: "Oct – Mar",
  AR: "Nov – Mar",
  PL: "May – Sep",
  NL: "Apr – Aug",
  SE: "Jun – Aug",
  NO: "Jun – Aug",
  NZ: "Dec – Feb",
  PT: "May – Sep",
  GR: "May – Oct",
  CH: "Jun – Sep",
  AT: "Jun – Sep",
  BE: "Jun – Sep",
  DK: "May – Aug",
  FI: "Jun – Aug",
  MY: "Mar – Sep",
  PH: "Nov – May",
  VN: "Nov – Apr",
  LK: "Dec – Mar",
  NP: "Oct – Nov",
  MV: "Nov – Apr",
  TW: "Oct – Nov",
  KR: "Apr – Jun",
  PE: "May – Sep",
  CO: "Dec – Mar",
  CL: "Nov – Mar",
  MA: "Mar – May",
  TN: "Mar – May",
  GH: "Nov – Mar",
  ET: "Oct – Feb",
  TZ: "Jun – Sep",
  UG: "Jun – Sep",
  QA: "Nov – Mar",
  KW: "Nov – Mar",
  BH: "Nov – Mar",
  OM: "Oct – Mar",
  JO: "Mar – May",
  IL: "Mar – May",
  RU: "May – Sep",
  UA: "May – Sep",
  CZ: "May – Sep",
  HU: "Apr – Oct",
  RO: "May – Sep",
  HR: "Jun – Sep",
  RS: "May – Sep",
  SK: "May – Sep",
  SI: "Jun – Sep",
  BG: "May – Sep",
  LT: "Jun – Aug",
  LV: "Jun – Aug",
  EE: "Jun – Aug",
  IS: "Jun – Aug",
  IE: "May – Sep",
  LU: "Jun – Sep",
};

// ─── Safety level ─────────────────────────────────────────────────────────────
export const safetyLevel: Record<string, SafetyLevel> = {
  IN: "caution",
  US: "safe",
  GB: "safe",
  FR: "safe",
  DE: "safe",
  JP: "safe",
  CN: "caution",
  AU: "safe",
  BR: "caution",
  CA: "safe",
  ZA: "caution",
  AE: "safe",
  SG: "safe",
  TH: "safe",
  IT: "safe",
  ES: "safe",
  MX: "caution",
  ID: "caution",
  NG: "high-risk",
  EG: "caution",
  KE: "caution",
  TR: "caution",
  SA: "caution",
  AR: "caution",
  PL: "safe",
  NL: "safe",
  SE: "safe",
  NO: "safe",
  NZ: "safe",
  PT: "safe",
  GR: "safe",
  CH: "safe",
  AT: "safe",
  BE: "safe",
  DK: "safe",
  FI: "safe",
  MY: "safe",
  PH: "caution",
  VN: "safe",
  LK: "safe",
  NP: "safe",
  MV: "safe",
  TW: "safe",
  KR: "safe",
  PE: "caution",
  CO: "caution",
  CL: "safe",
  MA: "safe",
  TN: "caution",
  GH: "safe",
  ET: "caution",
  TZ: "safe",
  UG: "caution",
  QA: "safe",
  KW: "safe",
  BH: "safe",
  OM: "safe",
  JO: "safe",
  IL: "caution",
  RU: "high-risk",
  UA: "high-risk",
  CZ: "safe",
  HU: "safe",
  RO: "safe",
  HR: "safe",
  RS: "safe",
  SK: "safe",
  SI: "safe",
  BG: "safe",
  LT: "safe",
  LV: "safe",
  EE: "safe",
  IS: "safe",
  IE: "safe",
  LU: "safe",
};

// ─── Currency tips ─────────────────────────────────────────────────────────────
export const currencyTip: Record<string, string> = {
  IN: "UPI & cards widely accepted",
  US: "Cards everywhere, no forex fees",
  GB: "Contactless cards standard",
  FR: "Cards & euros widely accepted",
  DE: "Carry cash — many shops card-only",
  JP: "Cash preferred; get yen on arrival",
  CN: "WeChat/Alipay; carry yuan",
  AU: "Cards widely accepted",
  BR: "Carry reais; card surcharges common",
  CA: "Cards accepted everywhere",
  ZA: "Cards OK; carry rand for markets",
  AE: "Cards & dirhams widely accepted",
  SG: "Cards & PayNow accepted widely",
  TH: "Carry baht; ATMs widely available",
  IT: "Cards accepted; cash for small tips",
  ES: "Cards standard; some tapas bars cash",
  MX: "Pesos preferred; USD widely accepted",
  ID: "Carry rupiah; cash for rural areas",
  NG: "Cash preferred; ATMs in cities",
  EG: "Carry Egyptian pounds; USD accepted",
  KE: "M-Pesa widely used; carry shillings",
  TR: "Cards OK; carry lira for bazaars",
  SA: "Cards & riyals widely accepted",
  AR: "USD in demand; check blue rate",
  PL: "Carry zloty; cards widely accepted",
  NL: "Cards & iDEAL standard; no cash fees",
  SE: "Cashless society; cards only",
  NO: "Nearly cashless; cards everywhere",
  NZ: "Cards widely accepted",
  PT: "Cards & euros standard",
  GR: "Cards OK; carry cash for islands",
  CH: "Francs preferred; cards accepted",
  AT: "Cards & euros widely accepted",
  BE: "Cards & euros standard",
  DK: "MobilePay & cards everywhere",
  FI: "Nearly cashless; Visa/MC standard",
  MY: "Cards & ringgit widely accepted",
  PH: "Pesos preferred; GCash popular",
  VN: "Carry dong; USD not always accepted",
  LK: "Carry rupees; ATMs in cities",
  NP: "Carry rupees; limited ATMs trekking",
  MV: "USD & cards at resorts",
  TW: "Carry NT dollars; cards in cities",
  KR: "T-money card & Korean Won",
  PE: "Carry soles; USD accepted tourist spots",
  CO: "Cards in cities; pesos for markets",
  CL: "Cards widely accepted; pesos",
  MA: "Carry dirhams; cards in cities",
  TN: "Carry dinars; limited card use",
  GH: "Cedis; mobile money popular",
  ET: "Carry birr; limited ATMs outside Addis",
  TZ: "Carry shillings; USD for safaris",
  UG: "Carry shillings; mobile money popular",
  QA: "Cards & riyals everywhere",
  KW: "Cards & dinars widely accepted",
  BH: "Cards & dinars widely accepted",
  OM: "Cards & riyals widely accepted",
  JO: "Cards & dinars widely accepted",
  IL: "Cards widely accepted; shekel",
  RU: "International cards blocked; carry rubles",
  UA: "Hryvnia; international cards limited in some areas",
  CZ: "Carry koruna; cards in cities",
  HU: "Carry forint; cards accepted",
  RO: "Carry leu; cards in cities",
  HR: "Euro since 2023; cards widely accepted",
  RS: "Carry dinar; cards in cities",
  SK: "Cards & euros widely accepted",
  SI: "Cards & euros widely accepted",
  BG: "Carry lev; cards in cities",
  LT: "Cards & euros widely accepted",
  LV: "Cards & euros widely accepted",
  EE: "Cashless leader; cards everywhere",
  IS: "Cards only; kronur rarely used",
  IE: "Cards & euros widely accepted",
  LU: "Cards & euros widely accepted",
};

// ─── Known for ───────────────────────────────────────────────────────────────
export const knownFor: Record<string, KnownForItem[]> = {
  IN: [
    { emoji: "🕌", label: "Taj Mahal" },
    { emoji: "🍛", label: "Cuisine" },
    { emoji: "🎭", label: "Bollywood" },
    { emoji: "🛕", label: "Temples" },
    { emoji: "🐯", label: "Tigers" },
  ],
  US: [
    { emoji: "🗽", label: "NYC" },
    { emoji: "🎬", label: "Hollywood" },
    { emoji: "🏔", label: "National Parks" },
    { emoji: "🎸", label: "Music" },
    { emoji: "🍔", label: "Food Culture" },
  ],
  GB: [
    { emoji: "👑", label: "Royalty" },
    { emoji: "🏰", label: "Castles" },
    { emoji: "🎭", label: "Theatre" },
    { emoji: "🍺", label: "Pubs" },
    { emoji: "🔬", label: "Science" },
  ],
  FR: [
    { emoji: "🗼", label: "Eiffel Tower" },
    { emoji: "🍷", label: "Wine" },
    { emoji: "🥐", label: "Cuisine" },
    { emoji: "🎨", label: "Art" },
    { emoji: "👗", label: "Fashion" },
  ],
  DE: [
    { emoji: "🍺", label: "Beer" },
    { emoji: "🚗", label: "Engineering" },
    { emoji: "🎄", label: "Christmas Markets" },
    { emoji: "🏰", label: "Castles" },
    { emoji: "🎶", label: "Classical Music" },
  ],
  JP: [
    { emoji: "🌸", label: "Cherry Blossom" },
    { emoji: "🗻", label: "Mt. Fuji" },
    { emoji: "🍣", label: "Cuisine" },
    { emoji: "⛩", label: "Temples" },
    { emoji: "🤖", label: "Technology" },
  ],
  CN: [
    { emoji: "🏯", label: "Great Wall" },
    { emoji: "🐉", label: "Culture" },
    { emoji: "🥟", label: "Cuisine" },
    { emoji: "🏮", label: "Festivals" },
    { emoji: "🧧", label: "History" },
  ],
  AU: [
    { emoji: "🦘", label: "Wildlife" },
    { emoji: "🏖", label: "Beaches" },
    { emoji: "🪃", label: "Outback" },
    { emoji: "🤿", label: "Great Barrier Reef" },
    { emoji: "🌆", label: "Sydney Opera House" },
  ],
  BR: [
    { emoji: "🥁", label: "Carnival" },
    { emoji: "⚽", label: "Football" },
    { emoji: "🌴", label: "Amazon" },
    { emoji: "🏖", label: "Beaches" },
    { emoji: "🌊", label: "Rio" },
  ],
  CA: [
    { emoji: "🍁", label: "Nature" },
    { emoji: "🏔", label: "Rockies" },
    { emoji: "🌊", label: "Niagara Falls" },
    { emoji: "🐻", label: "Wildlife" },
    { emoji: "🎿", label: "Skiing" },
  ],
  ZA: [
    { emoji: "🦁", label: "Safaris" },
    { emoji: "🌊", label: "Cape Town" },
    { emoji: "🍷", label: "Wine Estates" },
    { emoji: "🏔", label: "Table Mountain" },
    { emoji: "🌍", label: "Rainbow Nation" },
  ],
  AE: [
    { emoji: "🏙", label: "Burj Khalifa" },
    { emoji: "🛍", label: "Shopping" },
    { emoji: "🏜", label: "Desert" },
    { emoji: "⛵", label: "Dhow Cruises" },
    { emoji: "🌟", label: "Luxury" },
  ],
  SG: [
    { emoji: "🌃", label: "Marina Bay" },
    { emoji: "🍜", label: "Hawker Food" },
    { emoji: "🌿", label: "Gardens" },
    { emoji: "✈️", label: "Changi Airport" },
    { emoji: "🏙", label: "Skyline" },
  ],
  TH: [
    { emoji: "🛕", label: "Temples" },
    { emoji: "🏖", label: "Islands" },
    { emoji: "🍜", label: "Street Food" },
    { emoji: "🐘", label: "Elephants" },
    { emoji: "🤿", label: "Diving" },
  ],
  IT: [
    { emoji: "🏛", label: "Rome" },
    { emoji: "🍕", label: "Pizza & Pasta" },
    { emoji: "🎨", label: "Renaissance Art" },
    { emoji: "🛶", label: "Venice" },
    { emoji: "🏔", label: "Dolomites" },
  ],
  ES: [
    { emoji: "💃", label: "Flamenco" },
    { emoji: "🍷", label: "Wine & Tapas" },
    { emoji: "🏖", label: "Beaches" },
    { emoji: "🎨", label: "Gaudí" },
    { emoji: "⚽", label: "Football" },
  ],
  MX: [
    { emoji: "🌮", label: "Tacos" },
    { emoji: "🏛", label: "Mayan Ruins" },
    { emoji: "🎭", label: "Día de Muertos" },
    { emoji: "🏖", label: "Cancún" },
    { emoji: "🎶", label: "Mariachi" },
  ],
  ID: [
    { emoji: "🌋", label: "Volcanoes" },
    { emoji: "🏖", label: "Bali Beaches" },
    { emoji: "🦧", label: "Orangutans" },
    { emoji: "🛕", label: "Borobudur" },
    { emoji: "🍚", label: "Cuisine" },
  ],
  NG: [
    { emoji: "🎵", label: "Afrobeats" },
    { emoji: "🎬", label: "Nollywood" },
    { emoji: "🌍", label: "Culture" },
    { emoji: "🍲", label: "Cuisine" },
    { emoji: "🏙", label: "Lagos" },
  ],
  EG: [
    { emoji: "🏛", label: "Pyramids" },
    { emoji: "🚢", label: "Nile Cruise" },
    { emoji: "🐪", label: "Sahara" },
    { emoji: "🤿", label: "Red Sea" },
    { emoji: "🏺", label: "Antiquities" },
  ],
  KE: [
    { emoji: "🦁", label: "Maasai Mara" },
    { emoji: "🏔", label: "Mt. Kenya" },
    { emoji: "🌅", label: "Safari" },
    { emoji: "🏖", label: "Coast" },
    { emoji: "🌍", label: "Culture" },
  ],
  TR: [
    { emoji: "🕌", label: "Istanbul" },
    { emoji: "🎈", label: "Cappadocia" },
    { emoji: "🌊", label: "Aegean Coast" },
    { emoji: "🍢", label: "Cuisine" },
    { emoji: "🏺", label: "History" },
  ],
  SA: [
    { emoji: "🕋", label: "Mecca & Medina" },
    { emoji: "🏜", label: "Rub' al Khali" },
    { emoji: "🌃", label: "Riyadh" },
    { emoji: "🏛", label: "AlUla" },
    { emoji: "🌟", label: "Vision 2030" },
  ],
  AR: [
    { emoji: "🥩", label: "Asado" },
    { emoji: "💃", label: "Tango" },
    { emoji: "🏔", label: "Andes" },
    { emoji: "🧉", label: "Mate" },
    { emoji: "🌊", label: "Patagonia" },
  ],
  PL: [
    { emoji: "🏰", label: "Krakow" },
    { emoji: "🥟", label: "Pierogi" },
    { emoji: "🌲", label: "Forests" },
    { emoji: "🎶", label: "Chopin" },
    { emoji: "🏛", label: "History" },
  ],
  NL: [
    { emoji: "🌷", label: "Tulips" },
    { emoji: "🚲", label: "Cycling" },
    { emoji: "🎨", label: "Van Gogh" },
    { emoji: "⛵", label: "Canals" },
    { emoji: "🧀", label: "Cheese" },
  ],
  SE: [
    { emoji: "🌌", label: "Northern Lights" },
    { emoji: "🏔", label: "Lapland" },
    { emoji: "🎵", label: "Music" },
    { emoji: "🪵", label: "Forests" },
    { emoji: "🏡", label: "Fika" },
  ],
  NO: [
    { emoji: "🌊", label: "Fjords" },
    { emoji: "🌌", label: "Aurora Borealis" },
    { emoji: "⛷", label: "Skiing" },
    { emoji: "🐳", label: "Whale Watching" },
    { emoji: "🎿", label: "Svalbard" },
  ],
  NZ: [
    { emoji: "🏔", label: "South Island" },
    { emoji: "🧙", label: "LOTR Locations" },
    { emoji: "🦅", label: "Wildlife" },
    { emoji: "🌊", label: "Milford Sound" },
    { emoji: "🏉", label: "Rugby" },
  ],
  PT: [
    { emoji: "🎵", label: "Fado" },
    { emoji: "🛶", label: "Lisbon" },
    { emoji: "🍷", label: "Port Wine" },
    { emoji: "🏖", label: "Algarve" },
    { emoji: "🧭", label: "Age of Discovery" },
  ],
  GR: [
    { emoji: "🏛", label: "Acropolis" },
    { emoji: "🌊", label: "Santorini" },
    { emoji: "🐟", label: "Cuisine" },
    { emoji: "⛵", label: "Islands" },
    { emoji: "📜", label: "Philosophy" },
  ],
  CH: [
    { emoji: "🏔", label: "Alps" },
    { emoji: "🍫", label: "Chocolate" },
    { emoji: "⌚", label: "Watches" },
    { emoji: "🎿", label: "Skiing" },
    { emoji: "🏦", label: "Banking" },
  ],
  AT: [
    { emoji: "🎶", label: "Mozart & Strauss" },
    { emoji: "🏰", label: "Palaces" },
    { emoji: "⛷", label: "Skiing" },
    { emoji: "☕", label: "Coffee Houses" },
    { emoji: "🏙", label: "Vienna" },
  ],
  BE: [
    { emoji: "🍫", label: "Chocolate" },
    { emoji: "🍺", label: "Beer" },
    { emoji: "🧇", label: "Waffles" },
    { emoji: "🏛", label: "Bruges" },
    { emoji: "🇪🇺", label: "EU Capital" },
  ],
  DK: [
    { emoji: "🧜", label: "Little Mermaid" },
    { emoji: "🍽", label: "New Nordic Cuisine" },
    { emoji: "🏰", label: "Castles" },
    { emoji: "🚲", label: "Cycling Culture" },
    { emoji: "😊", label: "Hygge" },
  ],
  FI: [
    { emoji: "🧖", label: "Sauna" },
    { emoji: "🌌", label: "Northern Lights" },
    { emoji: "🎅", label: "Santa Claus Village" },
    { emoji: "🌲", label: "Forests & Lakes" },
    { emoji: "🦌", label: "Reindeer" },
  ],
  MY: [
    { emoji: "🏙", label: "Petronas Towers" },
    { emoji: "🍜", label: "Street Food" },
    { emoji: "🌴", label: "Rainforest" },
    { emoji: "🦧", label: "Borneo Wildlife" },
    { emoji: "🕌", label: "Culture" },
  ],
  PH: [
    { emoji: "🏖", label: "Beaches" },
    { emoji: "🌋", label: "Mayon Volcano" },
    { emoji: "🏄", label: "Surfing" },
    { emoji: "🐚", label: "Coral Reefs" },
    { emoji: "🎉", label: "Festivals" },
  ],
  VN: [
    { emoji: "🏖", label: "Ha Long Bay" },
    { emoji: "🍜", label: "Pho" },
    { emoji: "🛵", label: "Hanoi Streets" },
    { emoji: "🌾", label: "Rice Terraces" },
    { emoji: "🏛", label: "Hoi An Old Town" },
  ],
  LK: [
    { emoji: "🐘", label: "Elephants" },
    { emoji: "🍵", label: "Ceylon Tea" },
    { emoji: "🌴", label: "Beaches" },
    { emoji: "🏯", label: "Sigiriya Rock" },
    { emoji: "🦚", label: "Wildlife" },
  ],
  NP: [
    { emoji: "🏔", label: "Himalayas" },
    { emoji: "🧗", label: "Everest Trek" },
    { emoji: "🛕", label: "Kathmandu Temples" },
    { emoji: "🦅", label: "Wildlife" },
    { emoji: "☮️", label: "Spirituality" },
  ],
  MV: [
    { emoji: "🏝", label: "Overwater Bungalows" },
    { emoji: "🤿", label: "Diving" },
    { emoji: "🦈", label: "Marine Life" },
    { emoji: "🌊", label: "Turquoise Lagoons" },
    { emoji: "🌅", label: "Sunsets" },
  ],
  TW: [
    { emoji: "🥟", label: "Night Markets" },
    { emoji: "🏮", label: "Lantern Festival" },
    { emoji: "🌿", label: "Taroko Gorge" },
    { emoji: "🏛", label: "National Palace Museum" },
    { emoji: "🧋", label: "Bubble Tea" },
  ],
  KR: [
    { emoji: "🎵", label: "K-Pop" },
    { emoji: "🍜", label: "Korean BBQ" },
    { emoji: "🏯", label: "Palaces" },
    { emoji: "🌸", label: "Cherry Blossoms" },
    { emoji: "💻", label: "Tech Culture" },
  ],
  PE: [
    { emoji: "🏛", label: "Machu Picchu" },
    { emoji: "🌊", label: "Amazon River" },
    { emoji: "🦙", label: "Llamas" },
    { emoji: "🍽", label: "Gastronomy" },
    { emoji: "🗿", label: "Nazca Lines" },
  ],
  CO: [
    { emoji: "☕", label: "Coffee" },
    { emoji: "🌺", label: "Flowers" },
    { emoji: "🎶", label: "Salsa" },
    { emoji: "🏔", label: "Andes" },
    { emoji: "🌴", label: "Caribbean Coast" },
  ],
  CL: [
    { emoji: "🏜", label: "Atacama Desert" },
    { emoji: "🌊", label: "Patagonia" },
    { emoji: "🗿", label: "Easter Island" },
    { emoji: "🍷", label: "Wine" },
    { emoji: "🏔", label: "Andes" },
  ],
  MA: [
    { emoji: "🕌", label: "Mosques" },
    { emoji: "🏪", label: "Medinas & Souks" },
    { emoji: "🐪", label: "Sahara Desert" },
    { emoji: "🌺", label: "Marrakech" },
    { emoji: "🏔", label: "Atlas Mountains" },
  ],
  TN: [
    { emoji: "🏛", label: "Carthage Ruins" },
    { emoji: "🏜", label: "Sahara" },
    { emoji: "🏖", label: "Mediterranean Beaches" },
    { emoji: "🍋", label: "Cuisine" },
    { emoji: "🕌", label: "Medinas" },
  ],
  GH: [
    { emoji: "🏯", label: "Cape Coast Castle" },
    { emoji: "🥁", label: "Music & Dance" },
    { emoji: "🌍", label: "Kente Culture" },
    { emoji: "🌴", label: "Wildlife" },
    { emoji: "😊", label: "Hospitality" },
  ],
  ET: [
    { emoji: "☕", label: "Coffee Origin" },
    { emoji: "🕍", label: "Rock-Hewn Churches" },
    { emoji: "🏔", label: "Simien Mountains" },
    { emoji: "🦁", label: "Wildlife" },
    { emoji: "📜", label: "Ancient Civilizations" },
  ],
  TZ: [
    { emoji: "🦁", label: "Serengeti" },
    { emoji: "🏔", label: "Kilimanjaro" },
    { emoji: "🏝", label: "Zanzibar" },
    { emoji: "🐘", label: "Ngorongoro Crater" },
    { emoji: "🌅", label: "Safari" },
  ],
  UG: [
    { emoji: "🦍", label: "Mountain Gorillas" },
    { emoji: "🌊", label: "Source of the Nile" },
    { emoji: "🦁", label: "Queen Elizabeth NP" },
    { emoji: "🌺", label: "Bwindi Forest" },
    { emoji: "🐦", label: "Birding" },
  ],
  QA: [
    { emoji: "🏙", label: "Doha Skyline" },
    { emoji: "🏛", label: "Islamic Museum" },
    { emoji: "🏜", label: "Desert Dunes" },
    { emoji: "⚽", label: "World Cup 2022" },
    { emoji: "🌟", label: "Luxury" },
  ],
  KW: [
    { emoji: "🕌", label: "Grand Mosque" },
    { emoji: "🏙", label: "Kuwait City" },
    { emoji: "🏜", label: "Desert" },
    { emoji: "🛍", label: "Souks" },
    { emoji: "🌊", label: "Gulf Coast" },
  ],
  BH: [
    { emoji: "🏛", label: "Qal'at al-Bahrain" },
    { emoji: "🌴", label: "Tree of Life" },
    { emoji: "🏎", label: "F1 Grand Prix" },
    { emoji: "🛍", label: "Gold Souks" },
    { emoji: "🏖", label: "Beaches" },
  ],
  OM: [
    { emoji: "🏰", label: "Mutrah Fort" },
    { emoji: "🏜", label: "Wahiba Sands" },
    { emoji: "🌊", label: "Fjords" },
    { emoji: "🐢", label: "Turtle Reserve" },
    { emoji: "🕌", label: "Sultan Qaboos Mosque" },
  ],
  JO: [
    { emoji: "🏛", label: "Petra" },
    { emoji: "🌊", label: "Dead Sea" },
    { emoji: "🏜", label: "Wadi Rum" },
    { emoji: "🕌", label: "Amman" },
    { emoji: "🏺", label: "Ancient History" },
  ],
  IL: [
    { emoji: "🕍", label: "Jerusalem" },
    { emoji: "🌊", label: "Dead Sea" },
    { emoji: "🏖", label: "Tel Aviv Beach" },
    { emoji: "🍆", label: "Cuisine" },
    { emoji: "📜", label: "Holy Sites" },
  ],
  RU: [
    { emoji: "🏰", label: "Kremlin" },
    { emoji: "🎭", label: "Bolshoi Ballet" },
    { emoji: "🌨", label: "Trans-Siberian Railway" },
    { emoji: "🎨", label: "Hermitage Museum" },
    { emoji: "🧅", label: "Cuisine" },
  ],
  UA: [
    { emoji: "🌻", label: "Sunflower Fields" },
    { emoji: "🏙", label: "Kyiv" },
    { emoji: "🏰", label: "Lviv Old Town" },
    { emoji: "🎭", label: "Culture" },
    { emoji: "🌊", label: "Black Sea" },
  ],
  CZ: [
    { emoji: "🍺", label: "Bohemian Beer" },
    { emoji: "🏰", label: "Prague Castle" },
    { emoji: "🎶", label: "Classical Music" },
    { emoji: "🌉", label: "Charles Bridge" },
    { emoji: "🏛", label: "Old Town" },
  ],
  HU: [
    { emoji: "🧖", label: "Thermal Baths" },
    { emoji: "🏰", label: "Buda Castle" },
    { emoji: "🎻", label: "Folk Music" },
    { emoji: "🌉", label: "Chain Bridge" },
    { emoji: "🍷", label: "Tokaj Wine" },
  ],
  RO: [
    { emoji: "🧛", label: "Dracula's Castle" },
    { emoji: "🏔", label: "Carpathians" },
    { emoji: "🌲", label: "Forests" },
    { emoji: "🏰", label: "Medieval Towns" },
    { emoji: "🌍", label: "Culture" },
  ],
  HR: [
    { emoji: "🌊", label: "Adriatic Coast" },
    { emoji: "🏛", label: "Dubrovnik" },
    { emoji: "🌊", label: "Plitvice Lakes" },
    { emoji: "⚽", label: "Football" },
    { emoji: "🍷", label: "Dalmatian Wine" },
  ],
  RS: [
    { emoji: "🏙", label: "Belgrade Nightlife" },
    { emoji: "🏰", label: "Kalemegdan Fortress" },
    { emoji: "🎶", label: "Exit Festival" },
    { emoji: "🌊", label: "Danube" },
    { emoji: "🍷", label: "Wine" },
  ],
  SK: [
    { emoji: "🏰", label: "Spiš Castle" },
    { emoji: "🏔", label: "High Tatras" },
    { emoji: "🍺", label: "Beer" },
    { emoji: "🌲", label: "Nature" },
    { emoji: "🛕", label: "Folk Heritage" },
  ],
  SI: [
    { emoji: "🏰", label: "Bled Castle" },
    { emoji: "🌊", label: "Soča Valley" },
    { emoji: "🌿", label: "Green Country" },
    { emoji: "🏔", label: "Julian Alps" },
    { emoji: "🍷", label: "Wine" },
  ],
  BG: [
    { emoji: "🏔", label: "Rhodope Mountains" },
    { emoji: "🏖", label: "Black Sea" },
    { emoji: "🕌", label: "Rila Monastery" },
    { emoji: "🥗", label: "Cuisine" },
    { emoji: "🌹", label: "Rose Valley" },
  ],
  LT: [
    { emoji: "🏰", label: "Vilnius Old Town" },
    { emoji: "🌲", label: "Curonian Spit" },
    { emoji: "🎶", label: "Song Festival" },
    { emoji: "🏙", label: "Kaunas" },
    { emoji: "🌍", label: "Culture" },
  ],
  LV: [
    { emoji: "🏛", label: "Riga Art Nouveau" },
    { emoji: "🌲", label: "Gauja Valley" },
    { emoji: "🎶", label: "Song Festival" },
    { emoji: "🏖", label: "Jūrmala Beach" },
    { emoji: "🌍", label: "Culture" },
  ],
  EE: [
    { emoji: "🏰", label: "Tallinn Old Town" },
    { emoji: "💻", label: "Digital Society" },
    { emoji: "🌲", label: "Forests & Bogs" },
    { emoji: "🌊", label: "Islands" },
    { emoji: "🎶", label: "Song Festival" },
  ],
  IS: [
    { emoji: "🌋", label: "Volcanoes" },
    { emoji: "🌌", label: "Northern Lights" },
    { emoji: "♨️", label: "Hot Springs" },
    { emoji: "🏔", label: "Glaciers" },
    { emoji: "🐋", label: "Whale Watching" },
  ],
  IE: [
    { emoji: "🍀", label: "Cliffs of Moher" },
    { emoji: "🏰", label: "Castles" },
    { emoji: "🍺", label: "Pubs & Guinness" },
    { emoji: "🎶", label: "Traditional Music" },
    { emoji: "🌿", label: "Green Countryside" },
  ],
  LU: [
    { emoji: "🏰", label: "Luxembourg City" },
    { emoji: "🌲", label: "Ardennes" },
    { emoji: "🇪🇺", label: "EU Hub" },
    { emoji: "🍷", label: "Moselle Wine" },
    { emoji: "🌉", label: "Bridges" },
  ],
};

// ─── Top experience ───────────────────────────────────────────────────────────
export const topExperience: Record<string, string> = {
  IN: "Watch sunrise at the Taj Mahal in Agra",
  US: "Road-trip along Route 66 or hike the Grand Canyon",
  GB: "Stroll through the Tower of London and Westminster",
  FR: "See the Eiffel Tower sparkle at night in Paris",
  DE: "Visit a fairy-tale Bavarian castle like Neuschwanstein",
  JP: "Hike to the Fushimi Inari shrine gates at dawn",
  CN: "Walk the Great Wall at Mutianyu at sunrise",
  AU: "Snorkel the Great Barrier Reef off Cairns",
  BR: "Dance at Rio Carnival or cruise the Amazon River",
  CA: "Watch the Northern Lights over Banff National Park",
  ZA: "Spot the Big Five on a Kruger National Park safari",
  AE: "Ascend the Burj Khalifa for a skyline view at dusk",
  SG: "Watch the nightly Gardens by the Bay light show",
  TH: "Explore the temples of Chiang Mai by tuk-tuk",
  IT: "Toss a coin in the Trevi Fountain and wander Rome",
  ES: "See Gaudí's Sagrada Família at the golden hour",
  MX: "Explore the ancient Mayan ruins of Chichen Itza",
  ID: "Watch sunrise from Mount Batur over Bali's caldera",
  NG: "Experience the energy and cuisine of Lagos Island",
  EG: "Sail down the Nile on a traditional felucca at sunset",
  KE: "Witness the Great Migration in the Maasai Mara",
  TR: "Drift over Cappadocia in a hot-air balloon at sunrise",
  SA: "Explore the ancient rose-red city of AlUla at dusk",
  AR: "Watch a live tango show and taste asado in Buenos Aires",
  PL: "Walk the historic streets of Krakow's Old Town",
  NL: "Cycle through the tulip fields of Keukenhof in bloom",
  SE: "Chase the Northern Lights in Swedish Lapland",
  NO: "Cruise through the dramatic Geirangerfjord",
  NZ: "Cruise Milford Sound and hike the Routeburn Track",
  PT: "Ride Tram 28 through Lisbon's historic Alfama district",
  GR: "Watch the iconic Santorini sunset from Oia",
  CH: "Take the Glacier Express through the Swiss Alps",
  AT: "Attend a classical concert in Vienna's Musikverein",
  BE: "Discover the medieval canals of Bruges on foot",
  DK: "Explore colorful Nyhavn harbour by boat in Copenhagen",
  FI: "Spend a night in a glass igloo under the Northern Lights",
  MY: "Explore Borneo's rainforest for orangutans and pygmy elephants",
  PH: "Island-hop through the breathtaking Bacuit Archipelago",
  VN: "Cruise through the limestone karsts of Ha Long Bay",
  LK: "Climb Sigiriya Rock Fortress at sunrise",
  NP: "Trek to Everest Base Camp through Sherpa villages",
  MV: "Snorkel with manta rays in a turquoise Maldivian lagoon",
  TW: "Explore Jiufen's lantern-lit streets after dark",
  KR: "Witness the cherry blossoms at Gyeongbokgung Palace",
  PE: "Trek the Inca Trail to Machu Picchu at sunrise",
  CO: "Sip coffee on a finca in the Coffee Triangle",
  CL: "Stargaze in the Atacama Desert — the clearest skies on Earth",
  MA: "Get lost in the labyrinthine souks of Marrakech",
  TN: "Watch the sun set over the Sahara from a desert camp",
  GH: "Visit Cape Coast Castle and pay tribute to history",
  ET: "Explore the ancient rock-hewn churches of Lalibela",
  TZ: "Witness the Great Migration on the Serengeti plains",
  UG: "Trek through Bwindi Forest for a gorilla encounter",
  QA: "Explore the Museum of Islamic Art along Doha Corniche",
  KW: "Visit the Grand Mosque and walk through the historic souk",
  BH: "Watch the Formula 1 race under the lights at Bahrain International Circuit",
  OM: "Sleep under the stars in the Wahiba Sands desert",
  JO: "Explore the rose-red Treasury of Petra by candlelight",
  IL: "Walk the Old City of Jerusalem through its four quarters",
  RU: "Admire the onion domes of St. Basil's Cathedral on Red Square",
  UA: "Stroll the cobblestone streets of Lviv's old town",
  CZ: "Walk across the Charles Bridge in misty early-morning Prague",
  HU: "Soak in a thermal bath and watch dusk over the Danube",
  RO: "Drive the Transfăgărășan mountain road through Transylvania",
  HR: "Walk the medieval walls of Dubrovnik at sunset",
  RS: "Dance the night away in a river barge club on the Danube",
  SK: "Hike through the High Tatras to Rysy peak",
  SI: "Row across the glacial Lake Bled at dawn",
  BG: "Visit Rila Monastery nestled in the Rhodope Mountains",
  LT: "Explore the baroque splendour of Vilnius Old Town",
  LV: "Admire Art Nouveau architecture on a stroll through Riga",
  EE: "Walk the medieval walls of Tallinn's Old Town at dusk",
  IS: "Bathe in the Blue Lagoon beneath the midnight sun",
  IE: "Stand on the Cliffs of Moher as the Atlantic swells below",
  LU: "Walk the ramparts of Luxembourg City's UNESCO fortress",
};

// ─── Fallback defaults ────────────────────────────────────────────────────────
export const DEFAULT_VISA: VisaStatus = "required";
export const DEFAULT_BEST_TIME = "Check local conditions";
export const DEFAULT_SAFETY: SafetyLevel = "caution";
export const DEFAULT_CURRENCY_TIP = "Carry some local cash";
export const DEFAULT_KNOWN_FOR: KnownForItem[] = [
  { emoji: "🌍", label: "Culture" },
  { emoji: "🏛", label: "History" },
];
export const DEFAULT_TOP_EXPERIENCE = "Explore the local culture and cuisine";
