// Travel & Culture data keyed by ISO alpha-2 country code
// Visa status is for Indian passport holders

export type VisaStatus = "free" | "on-arrival" | "e-visa" | "required";
export type SafetyLevel = "safe" | "caution" | "high-risk";

export interface KnownForItem {
  emoji: string;
  label: string;
}

// ─── Visa on arrival / e-visa / visa-free for Indian passport ────────────────
export const visaForIndian: Record<string, VisaStatus> = {
  IN: "free",
  US: "required",
  GB: "required",
  FR: "required",
  DE: "required",
  JP: "required",
  CN: "required",
  AU: "required",
  BR: "free",
  CA: "required",
  ZA: "required",
  AE: "on-arrival",
  SG: "required",
  TH: "on-arrival",
  IT: "required",
  ES: "required",
  MX: "free",
  ID: "free",
  NG: "on-arrival",
  EG: "on-arrival",
  KE: "e-visa",
  TR: "e-visa",
  SA: "e-visa",
  AR: "free",
  PL: "required",
  NL: "required",
  SE: "required",
  NO: "required",
  NZ: "e-visa",
  PT: "required",
  GR: "required",
  CH: "required",
  AT: "required",
  BE: "required",
  DK: "required",
  FI: "required",
  MY: "free",
  PH: "free",
  VN: "e-visa",
  LK: "e-visa",
  NP: "free",
  MV: "on-arrival",
  TW: "required",
  KR: "required",
  PE: "free",
  CO: "free",
  CL: "free",
  MA: "free",
  TN: "on-arrival",
  GH: "on-arrival",
  ET: "on-arrival",
  TZ: "on-arrival",
  UG: "on-arrival",
  QA: "on-arrival",
  KW: "required",
  BH: "on-arrival",
  OM: "on-arrival",
  JO: "on-arrival",
  IL: "required",
  RU: "required",
  UA: "free",
  CZ: "required",
  HU: "required",
  RO: "required",
  HR: "required",
  RS: "free",
  SK: "required",
  SI: "required",
  BG: "required",
  LT: "required",
  LV: "required",
  EE: "required",
  IS: "required",
  IE: "required",
  LU: "required",
};

// ─── Best time to visit ───────────────────────────────────────────────────────
export const bestTime: Record<string, string> = {
  IN: "Oct – Mar",
  US: "Apr – Jun",
  GB: "May – Sep",
  FR: "Apr – Oct",
  DE: "May – Sep",
  JP: "Mar – May",
  CN: "Apr – Jun",
  AU: "Sep – Nov",
  BR: "Apr – Jun",
  CA: "Jun – Aug",
  ZA: "May – Sep",
  AE: "Nov – Mar",
  SG: "Feb – Apr",
  TH: "Nov – Mar",
  IT: "Apr – Jun",
  ES: "Apr – Jun",
  MX: "Dec – Apr",
  ID: "Apr – Oct",
  NG: "Nov – Feb",
  EG: "Oct – Apr",
  KE: "Jul – Oct",
  TR: "Apr – Jun",
  SA: "Oct – Mar",
  AR: "Nov – Mar",
  PL: "May – Sep",
  NL: "Apr – Aug",
  SE: "Jun – Aug",
  NO: "Jun – Aug",
  NZ: "Dec – Feb",
  PT: "May – Sep",
  GR: "May – Oct",
  CH: "Jun – Sep",
  AT: "Jun – Sep",
  BE: "Jun – Sep",
  DK: "May – Aug",
  FI: "Jun – Aug",
  MY: "Mar – Sep",
  PH: "Nov – May",
  VN: "Nov – Apr",
  LK: "Dec – Mar",
  NP: "Oct – Nov",
  MV: "Nov – Apr",
  TW: "Oct – Nov",
  KR: "Apr – Jun",
  PE: "May – Sep",
  CO: "Dec – Mar",
  CL: "Nov – Mar",
  MA: "Mar – May",
  TN: "Mar – May",
  GH: "Nov – Mar",
  ET: "Oct – Feb",
  TZ: "Jun – Sep",
  UG: "Jun – Sep",
  QA: "Nov – Mar",
  KW: "Nov – Mar",
  BH: "Nov – Mar",
  OM: "Oct – Mar",
  JO: "Mar – May",
  IL: "Mar – May",
  RU: "May – Sep",
  UA: "May – Sep",
  CZ: "May – Sep",
  HU: "Apr – Oct",
  RO: "May – Sep",
  HR: "Jun – Sep",
  RS: "May – Sep",
  SK: "May – Sep",
  SI: "Jun – Sep",
  BG: "May – Sep",
  LT: "Jun – Aug",
  LV: "Jun – Aug",
  EE: "Jun – Aug",
  IS: "Jun – Aug",
  IE: "May – Sep",
  LU: "Jun – Sep",
};

// ─── Safety level ─────────────────────────────────────────────────────────────
export const safetyLevel: Record<string, SafetyLevel> = {
  IN: "caution",
  US: "safe",
  GB: "safe",
  FR: "safe",
  DE: "safe",
  JP: "safe",
  CN: "caution",
  AU: "safe",
  BR: "caution",
  CA: "safe",
  ZA: "caution",
  AE: "safe",
  SG: "safe",
  TH: "safe",
  IT: "safe",
  ES: "safe",
  MX: "caution",
  ID: "caution",
  NG: "high-risk",
  EG: "caution",
  KE: "caution",
  TR: "caution",
  SA: "caution",
  AR: "caution",
  PL: "safe",
  NL: "safe",
  SE: "safe",
  NO: "safe",
  NZ: "safe",
  PT: "safe",
  GR: "safe",
  CH: "safe",
  AT: "safe",
  BE: "safe",
  DK: "safe",
  FI: "safe",
  MY: "safe",
  PH: "caution",
  VN: "safe",
  LK: "safe",
  NP: "safe",
  MV: "safe",
  TW: "safe",
  KR: "safe",
  PE: "caution",
  CO: "caution",
  CL: "safe",
  MA: "safe",
  TN: "caution",
  GH: "safe",
  ET: "caution",
  TZ: "safe",
  UG: "caution",
  QA: "safe",
  KW: "safe",
  BH: "safe",
  OM: "safe",
  JO: "safe",
  IL: "caution",
  RU: "high-risk",
  UA: "high-risk",
  CZ: "safe",
  HU: "safe",
  RO: "safe",
  HR: "safe",
  RS: "safe",
  SK: "safe",
  SI: "safe",
  BG: "safe",
  LT: "safe",
  LV: "safe",
  EE: "safe",
  IS: "safe",
  IE: "safe",
  LU: "safe",
};

// ─── Currency tips ─────────────────────────────────────────────────────────────
export const currencyTip: Record<string, string> = {
  IN: "UPI & cards widely accepted",
  US: "Cards everywhere, no forex fees",
  GB: "Contactless cards standard",
  FR: "Cards & euros widely accepted",
  DE: "Carry cash — many shops card-only",
  JP: "Cash preferred; get yen on arrival",
  CN: "WeChat/Alipay; carry yuan",
  AU: "Cards widely accepted",
  BR: "Carry reais; card surcharges common",
  CA: "Cards accepted everywhere",
  ZA: "Cards OK; carry rand for markets",
  AE: "Cards & dirhams widely accepted",
  SG: "Cards & PayNow accepted widely",
  TH: "Carry baht; ATMs widely available",
  IT: "Cards accepted; cash for small tips",
  ES: "Cards standard; some tapas bars cash",
  MX: "Pesos preferred; USD widely accepted",
  ID: "Carry rupiah; cash for rural areas",
  NG: "Cash preferred; ATMs in cities",
  EG: "Carry Egyptian pounds; USD accepted",
  KE: "M-Pesa widely used; carry shillings",
  TR: "Cards OK; carry lira for bazaars",
  SA: "Cards & riyals widely accepted",
  AR: "USD in demand; check blue rate",
  PL: "Carry zloty; cards widely accepted",
  NL: "Cards & iDEAL standard; no cash fees",
  SE: "Cashless society; cards only",
  NO: "Nearly cashless; cards everywhere",
  NZ: "Cards widely accepted",
  PT: "Cards & euros standard",
  GR: "Cards OK; carry cash for islands",
  CH: "Francs preferred; cards accepted",
  AT: "Cards & euros widely accepted",
  BE: "Cards & euros standard",
  DK: "MobilePay & cards everywhere",
  FI: "Nearly cashless; Visa/MC standard",
  MY: "Cards & ringgit widely accepted",
  PH: "Pesos preferred; GCash popular",
  VN: "Carry dong; USD not always accepted",
  LK: "Carry rupees; ATMs in cities",
  NP: "Carry rupees; limited ATMs trekking",
  MV: "USD & cards at resorts",
  TW: "Carry NT dollars; cards in cities",
  KR: "T-money card & Korean Won",
  PE: "Carry soles; USD accepted tourist spots",
  CO: "Cards in cities; pesos for markets",
  CL: "Cards widely accepted; pesos",
  MA: "Carry dirhams; cards in cities",
  TN: "Carry dinars; limited card use",
  GH: "Cedis; mobile money popular",
  ET: "Carry birr; limited ATMs outside Addis",
  TZ: "Carry shillings; USD for safaris",
  UG: "Carry shillings; mobile money popular",
  QA: "Cards & riyals everywhere",
  KW: "Cards & dinars widely accepted",
  BH: "Cards & dinars widely accepted",
  OM: "Cards & riyals widely accepted",
  JO: "Cards & dinars widely accepted",
  IL: "Cards widely accepted; shekel",
  RU: "International cards blocked; carry rubles",
  UA: "Hryvnia; international cards limited in some areas",
  CZ: "Carry koruna; cards in cities",
  HU: "Carry forint; cards accepted",
  RO: "Carry leu; cards in cities",
  HR: "Euro since 2023; cards widely accepted",
  RS: "Carry dinar; cards in cities",
  SK: "Cards & euros widely accepted",
  SI: "Cards & euros widely accepted",
  BG: "Carry lev; cards in cities",
  LT: "Cards & euros widely accepted",
  LV: "Cards & euros widely accepted",
  EE: "Cashless leader; cards everywhere",
  IS: "Cards only; kronur rarely used",
  IE: "Cards & euros widely accepted",
  LU: "Cards & euros widely accepted",
};

// ─── Known for ───────────────────────────────────────────────────────────────
export const knownFor: Record<string, KnownForItem[]> = {
  IN: [
    { emoji: "🕌", label: "Taj Mahal" },
    { emoji: "🍛", label: "Cuisine" },
    { emoji: "🎭", label: "Bollywood" },
    { emoji: "🛕", label: "Temples" },
    { emoji: "🐯", label: "Tigers" },
  ],
  US: [
    { emoji: "🗽", label: "NYC" },
    { emoji: "🎬", label: "Hollywood" },
    { emoji: "🏔", label: "National Parks" },
    { emoji: "🎸", label: "Music" },
    { emoji: "🍔", label: "Food Culture" },
  ],
  GB: [
    { emoji: "👑", label: "Royalty" },
    { emoji: "🏰", label: "Castles" },
    { emoji: "🎭", label: "Theatre" },
    { emoji: "🍺", label: "Pubs" },
    { emoji: "🔬", label: "Science" },
  ],
  FR: [
    { emoji: "🗼", label: "Eiffel Tower" },
    { emoji: "🍷", label: "Wine" },
    { emoji: "🥐", label: "Cuisine" },
    { emoji: "🎨", label: "Art" },
    { emoji: "👗", label: "Fashion" },
  ],
  DE: [
    { emoji: "🍺", label: "Beer" },
    { emoji: "🚗", label: "Engineering" },
    { emoji: "🎄", label: "Christmas Markets" },
    { emoji: "🏰", label: "Castles" },
    { emoji: "🎶", label: "Classical Music" },
  ],
  JP: [
    { emoji: "🌸", label: "Cherry Blossom" },
    { emoji: "🗻", label: "Mt. Fuji" },
    { emoji: "🍣", label: "Cuisine" },
    { emoji: "⛩", label: "Temples" },
    { emoji: "🤖", label: "Technology" },
  ],
  CN: [
    { emoji: "🏯", label: "Great Wall" },
    { emoji: "🐉", label: "Culture" },
    { emoji: "🥟", label: "Cuisine" },
    { emoji: "🏮", label: "Festivals" },
    { emoji: "🧧", label: "History" },
  ],
  AU: [
    { emoji: "🦘", label: "Wildlife" },
    { emoji: "🏖", label: "Beaches" },
    { emoji: "🪃", label: "Outback" },
    { emoji: "🤿", label: "Great Barrier Reef" },
    { emoji: "🌆", label: "Sydney Opera House" },
  ],
  BR: [
    { emoji: "🥁", label: "Carnival" },
    { emoji: "⚽", label: "Football" },
    { emoji: "🌴", label: "Amazon" },
    { emoji: "🏖", label: "Beaches" },
    { emoji: "🌊", label: "Rio" },
  ],
  CA: [
    { emoji: "🍁", label: "Nature" },
    { emoji: "🏔", label: "Rockies" },
    { emoji: "🌊", label: "Niagara Falls" },
    { emoji: "🐻", label: "Wildlife" },
    { emoji: "🎿", label: "Skiing" },
  ],
  ZA: [
    { emoji: "🦁", label: "Safaris" },
    { emoji: "🌊", label: "Cape Town" },
    { emoji: "🍷", label: "Wine Estates" },
    { emoji: "🏔", label: "Table Mountain" },
    { emoji: "🌍", label: "Rainbow Nation" },
  ],
  AE: [
    { emoji: "🏙", label: "Burj Khalifa" },
    { emoji: "🛍", label: "Shopping" },
    { emoji: "🏜", label: "Desert" },
    { emoji: "⛵", label: "Dhow Cruises" },
    { emoji: "🌟", label: "Luxury" },
  ],
  SG: [
    { emoji: "🌃", label: "Marina Bay" },
    { emoji: "🍜", label: "Hawker Food" },
    { emoji: "🌿", label: "Gardens" },
    { emoji: "✈️", label: "Changi Airport" },
    { emoji: "🏙", label: "Skyline" },
  ],
  TH: [
    { emoji: "🛕", label: "Temples" },
    { emoji: "🏖", label: "Islands" },
    { emoji: "🍜", label: "Street Food" },
    { emoji: "🐘", label: "Elephants" },
    { emoji: "🤿", label: "Diving" },
  ],
  IT: [
    { emoji: "🏛", label: "Rome" },
    { emoji: "🍕", label: "Pizza & Pasta" },
    { emoji: "🎨", label: "Renaissance Art" },
    { emoji: "🛶", label: "Venice" },
    { emoji: "🏔", label: "Dolomites" },
  ],
  ES: [
    { emoji: "💃", label: "Flamenco" },
    { emoji: "🍷", label: "Wine & Tapas" },
    { emoji: "🏖", label: "Beaches" },
    { emoji: "🎨", label: "Gaudí" },
    { emoji: "⚽", label: "Football" },
  ],
  MX: [
    { emoji: "🌮", label: "Tacos" },
    { emoji: "🏛", label: "Mayan Ruins" },
    { emoji: "🎭", label: "Día de Muertos" },
    { emoji: "🏖", label: "Cancún" },
    { emoji: "🎶", label: "Mariachi" },
  ],
  ID: [
    { emoji: "🌋", label: "Volcanoes" },
    { emoji: "🏖", label: "Bali Beaches" },
    { emoji: "🦧", label: "Orangutans" },
    { emoji: "🛕", label: "Borobudur" },
    { emoji: "🍚", label: "Cuisine" },
  ],
  NG: [
    { emoji: "🎵", label: "Afrobeats" },
    { emoji: "🎬", label: "Nollywood" },
    { emoji: "🌍", label: "Culture" },
    { emoji: "🍲", label: "Cuisine" },
    { emoji: "🏙", label: "Lagos" },
  ],
  EG: [
    { emoji: "🏛", label: "Pyramids" },
    { emoji: "🚢", label: "Nile Cruise" },
    { emoji: "🐪", label: "Sahara" },
    { emoji: "🤿", label: "Red Sea" },
    { emoji: "🏺", label: "Antiquities" },
  ],
  KE: [
    { emoji: "🦁", label: "Maasai Mara" },
    { emoji: "🏔", label: "Mt. Kenya" },
    { emoji: "🌅", label: "Safari" },
    { emoji: "🏖", label: "Coast" },
    { emoji: "🌍", label: "Culture" },
  ],
  TR: [
    { emoji: "🕌", label: "Istanbul" },
    { emoji: "🎈", label: "Cappadocia" },
    { emoji: "🌊", label: "Aegean Coast" },
    { emoji: "🍢", label: "Cuisine" },
    { emoji: "🏺", label: "History" },
  ],
  SA: [
    { emoji: "🕋", label: "Mecca & Medina" },
    { emoji: "🏜", label: "Rub' al Khali" },
    { emoji: "🌃", label: "Riyadh" },
    { emoji: "🏛", label: "AlUla" },
    { emoji: "🌟", label: "Vision 2030" },
  ],
  AR: [
    { emoji: "🥩", label: "Asado" },
    { emoji: "💃", label: "Tango" },
    { emoji: "🏔", label: "Andes" },
    { emoji: "🧉", label: "Mate" },
    { emoji: "🌊", label: "Patagonia" },
  ],
  PL: [
    { emoji: "🏰", label: "Krakow" },
    { emoji: "🥟", label: "Pierogi" },
    { emoji: "🌲", label: "Forests" },
    { emoji: "🎶", label: "Chopin" },
    { emoji: "🏛", label: "History" },
  ],
  NL: [
    { emoji: "🌷", label: "Tulips" },
    { emoji: "🚲", label: "Cycling" },
    { emoji: "🎨", label: "Van Gogh" },
    { emoji: "⛵", label: "Canals" },
    { emoji: "🧀", label: "Cheese" },
  ],
  SE: [
    { emoji: "🌌", label: "Northern Lights" },
    { emoji: "🏔", label: "Lapland" },
    { emoji: "🎵", label: "Music" },
    { emoji: "🪵", label: "Forests" },
    { emoji: "🏡", label: "Fika" },
  ],
  NO: [
    { emoji: "🌊", label: "Fjords" },
    { emoji: "🌌", label: "Aurora Borealis" },
    { emoji: "⛷", label: "Skiing" },
    { emoji: "🐳", label: "Whale Watching" },
    { emoji: "🎿", label: "Svalbard" },
  ],
  NZ: [
    { emoji: "🏔", label: "South Island" },
    { emoji: "🧙", label: "LOTR Locations" },
    { emoji: "🦅", label: "Wildlife" },
    { emoji: "🌊", label: "Milford Sound" },
    { emoji: "🏉", label: "Rugby" },
  ],
  PT: [
    { emoji: "🎵", label: "Fado" },
    { emoji: "🛶", label: "Lisbon" },
    { emoji: "🍷", label: "Port Wine" },
    { emoji: "🏖", label: "Algarve" },
    { emoji: "🧭", label: "Age of Discovery" },
  ],
  GR: [
    { emoji: "🏛", label: "Acropolis" },
    { emoji: "🌊", label: "Santorini" },
    { emoji: "🐟", label: "Cuisine" },
    { emoji: "⛵", label: "Islands" },
    { emoji: "📜", label: "Philosophy" },
  ],
  CH: [
    { emoji: "🏔", label: "Alps" },
    { emoji: "🍫", label: "Chocolate" },
    { emoji: "⌚", label: "Watches" },
    { emoji: "🎿", label: "Skiing" },
    { emoji: "🏦", label: "Banking" },
  ],
  AT: [
    { emoji: "🎶", label: "Mozart & Strauss" },
    { emoji: "🏰", label: "Palaces" },
    { emoji: "⛷", label: "Skiing" },
    { emoji: "☕", label: "Coffee Houses" },
    { emoji: "🏙", label: "Vienna" },
  ],
  BE: [
    { emoji: "🍫", label: "Chocolate" },
    { emoji: "🍺", label: "Beer" },
    { emoji: "🧇", label: "Waffles" },
    { emoji: "🏛", label: "Bruges" },
    { emoji: "🇪🇺", label: "EU Capital" },
  ],
  DK: [
    { emoji: "🧜", label: "Little Mermaid" },
    { emoji: "🍽", label: "New Nordic Cuisine" },
    { emoji: "🏰", label: "Castles" },
    { emoji: "🚲", label: "Cycling Culture" },
    { emoji: "😊", label: "Hygge" },
  ],
  FI: [
    { emoji: "🧖", label: "Sauna" },
    { emoji: "🌌", label: "Northern Lights" },
    { emoji: "🎅", label: "Santa Claus Village" },
    { emoji: "🌲", label: "Forests & Lakes" },
    { emoji: "🦌", label: "Reindeer" },
  ],
  MY: [
    { emoji: "🏙", label: "Petronas Towers" },
    { emoji: "🍜", label: "Street Food" },
    { emoji: "🌴", label: "Rainforest" },
    { emoji: "🦧", label: "Borneo Wildlife" },
    { emoji: "🕌", label: "Culture" },
  ],
  PH: [
    { emoji: "🏖", label: "Beaches" },
    { emoji: "🌋", label: "Mayon Volcano" },
    { emoji: "🏄", label: "Surfing" },
    { emoji: "🐚", label: "Coral Reefs" },
    { emoji: "🎉", label: "Festivals" },
  ],
  VN: [
    { emoji: "🏖", label: "Ha Long Bay" },
    { emoji: "🍜", label: "Pho" },
    { emoji: "🛵", label: "Hanoi Streets" },
    { emoji: "🌾", label: "Rice Terraces" },
    { emoji: "🏛", label: "Hoi An Old Town" },
  ],
  LK: [
    { emoji: "🐘", label: "Elephants" },
    { emoji: "🍵", label: "Ceylon Tea" },
    { emoji: "🌴", label: "Beaches" },
    { emoji: "🏯", label: "Sigiriya Rock" },
    { emoji: "🦚", label: "Wildlife" },
  ],
  NP: [
    { emoji: "🏔", label: "Himalayas" },
    { emoji: "🧗", label: "Everest Trek" },
    { emoji: "🛕", label: "Kathmandu Temples" },
    { emoji: "🦅", label: "Wildlife" },
    { emoji: "☮️", label: "Spirituality" },
  ],
  MV: [
    { emoji: "🏝", label: "Overwater Bungalows" },
    { emoji: "🤿", label: "Diving" },
    { emoji: "🦈", label: "Marine Life" },
    { emoji: "🌊", label: "Turquoise Lagoons" },
    { emoji: "🌅", label: "Sunsets" },
  ],
  TW: [
    { emoji: "🥟", label: "Night Markets" },
    { emoji: "🏮", label: "Lantern Festival" },
    { emoji: "🌿", label: "Taroko Gorge" },
    { emoji: "🏛", label: "National Palace Museum" },
    { emoji: "🧋", label: "Bubble Tea" },
  ],
  KR: [
    { emoji: "🎵", label: "K-Pop" },
    { emoji: "🍜", label: "Korean BBQ" },
    { emoji: "🏯", label: "Palaces" },
    { emoji: "🌸", label: "Cherry Blossoms" },
    { emoji: "💻", label: "Tech Culture" },
  ],
  PE: [
    { emoji: "🏛", label: "Machu Picchu" },
    { emoji: "🌊", label: "Amazon River" },
    { emoji: "🦙", label: "Llamas" },
    { emoji: "🍽", label: "Gastronomy" },
    { emoji: "🗿", label: "Nazca Lines" },
  ],
  CO: [
    { emoji: "☕", label: "Coffee" },
    { emoji: "🌺", label: "Flowers" },
    { emoji: "🎶", label: "Salsa" },
    { emoji: "🏔", label: "Andes" },
    { emoji: "🌴", label: "Caribbean Coast" },
  ],
  CL: [
    { emoji: "🏜", label: "Atacama Desert" },
    { emoji: "🌊", label: "Patagonia" },
    { emoji: "🗿", label: "Easter Island" },
    { emoji: "🍷", label: "Wine" },
    { emoji: "🏔", label: "Andes" },
  ],
  MA: [
    { emoji: "🕌", label: "Mosques" },
    { emoji: "🏪", label: "Medinas & Souks" },
    { emoji: "🐪", label: "Sahara Desert" },
    { emoji: "🌺", label: "Marrakech" },
    { emoji: "🏔", label: "Atlas Mountains" },
  ],
  TN: [
    { emoji: "🏛", label: "Carthage Ruins" },
    { emoji: "🏜", label: "Sahara" },
    { emoji: "🏖", label: "Mediterranean Beaches" },
    { emoji: "🍋", label: "Cuisine" },
    { emoji: "🕌", label: "Medinas" },
  ],
  GH: [
    { emoji: "🏯", label: "Cape Coast Castle" },
    { emoji: "🥁", label: "Music & Dance" },
    { emoji: "🌍", label: "Kente Culture" },
    { emoji: "🌴", label: "Wildlife" },
    { emoji: "😊", label: "Hospitality" },
  ],
  ET: [
    { emoji: "☕", label: "Coffee Origin" },
    { emoji: "🕍", label: "Rock-Hewn Churches" },
    { emoji: "🏔", label: "Simien Mountains" },
    { emoji: "🦁", label: "Wildlife" },
    { emoji: "📜", label: "Ancient Civilizations" },
  ],
  TZ: [
    { emoji: "🦁", label: "Serengeti" },
    { emoji: "🏔", label: "Kilimanjaro" },
    { emoji: "🏝", label: "Zanzibar" },
    { emoji: "🐘", label: "Ngorongoro Crater" },
    { emoji: "🌅", label: "Safari" },
  ],
  UG: [
    { emoji: "🦍", label: "Mountain Gorillas" },
    { emoji: "🌊", label: "Source of the Nile" },
    { emoji: "🦁", label: "Queen Elizabeth NP" },
    { emoji: "🌺", label: "Bwindi Forest" },
    { emoji: "🐦", label: "Birding" },
  ],
  QA: [
    { emoji: "🏙", label: "Doha Skyline" },
    { emoji: "🏛", label: "Islamic Museum" },
    { emoji: "🏜", label: "Desert Dunes" },
    { emoji: "⚽", label: "World Cup 2022" },
    { emoji: "🌟", label: "Luxury" },
  ],
  KW: [
    { emoji: "🕌", label: "Grand Mosque" },
    { emoji: "🏙", label: "Kuwait City" },
    { emoji: "🏜", label: "Desert" },
    { emoji: "🛍", label: "Souks" },
    { emoji: "🌊", label: "Gulf Coast" },
  ],
  BH: [
    { emoji: "🏛", label: "Qal'at al-Bahrain" },
    { emoji: "🌴", label: "Tree of Life" },
    { emoji: "🏎", label: "F1 Grand Prix" },
    { emoji: "🛍", label: "Gold Souks" },
    { emoji: "🏖", label: "Beaches" },
  ],
  OM: [
    { emoji: "🏰", label: "Mutrah Fort" },
    { emoji: "🏜", label: "Wahiba Sands" },
    { emoji: "🌊", label: "Fjords" },
    { emoji: "🐢", label: "Turtle Reserve" },
    { emoji: "🕌", label: "Sultan Qaboos Mosque" },
  ],
  JO: [
    { emoji: "🏛", label: "Petra" },
    { emoji: "🌊", label: "Dead Sea" },
    { emoji: "🏜", label: "Wadi Rum" },
    { emoji: "🕌", label: "Amman" },
    { emoji: "🏺", label: "Ancient History" },
  ],
  IL: [
    { emoji: "🕍", label: "Jerusalem" },
    { emoji: "🌊", label: "Dead Sea" },
    { emoji: "🏖", label: "Tel Aviv Beach" },
    { emoji: "🍆", label: "Cuisine" },
    { emoji: "📜", label: "Holy Sites" },
  ],
  RU: [
    { emoji: "🏰", label: "Kremlin" },
    { emoji: "🎭", label: "Bolshoi Ballet" },
    { emoji: "🌨", label: "Trans-Siberian Railway" },
    { emoji: "🎨", label: "Hermitage Museum" },
    { emoji: "🧅", label: "Cuisine" },
  ],
  UA: [
    { emoji: "🌻", label: "Sunflower Fields" },
    { emoji: "🏙", label: "Kyiv" },
    { emoji: "🏰", label: "Lviv Old Town" },
    { emoji: "🎭", label: "Culture" },
    { emoji: "🌊", label: "Black Sea" },
  ],
  CZ: [
    { emoji: "🍺", label: "Bohemian Beer" },
    { emoji: "🏰", label: "Prague Castle" },
    { emoji: "🎶", label: "Classical Music" },
    { emoji: "🌉", label: "Charles Bridge" },
    { emoji: "🏛", label: "Old Town" },
  ],
  HU: [
    { emoji: "🧖", label: "Thermal Baths" },
    { emoji: "🏰", label: "Buda Castle" },
    { emoji: "🎻", label: "Folk Music" },
    { emoji: "🌉", label: "Chain Bridge" },
    { emoji: "🍷", label: "Tokaj Wine" },
  ],
  RO: [
    { emoji: "🧛", label: "Dracula's Castle" },
    { emoji: "🏔", label: "Carpathians" },
    { emoji: "🌲", label: "Forests" },
    { emoji: "🏰", label: "Medieval Towns" },
    { emoji: "🌍", label: "Culture" },
  ],
  HR: [
    { emoji: "🌊", label: "Adriatic Coast" },
    { emoji: "🏛", label: "Dubrovnik" },
    { emoji: "🌊", label: "Plitvice Lakes" },
    { emoji: "⚽", label: "Football" },
    { emoji: "🍷", label: "Dalmatian Wine" },
  ],
  RS: [
    { emoji: "🏙", label: "Belgrade Nightlife" },
    { emoji: "🏰", label: "Kalemegdan Fortress" },
    { emoji: "🎶", label: "Exit Festival" },
    { emoji: "🌊", label: "Danube" },
    { emoji: "🍷", label: "Wine" },
  ],
  SK: [
    { emoji: "🏰", label: "Spiš Castle" },
    { emoji: "🏔", label: "High Tatras" },
    { emoji: "🍺", label: "Beer" },
    { emoji: "🌲", label: "Nature" },
    { emoji: "🛕", label: "Folk Heritage" },
  ],
  SI: [
    { emoji: "🏰", label: "Bled Castle" },
    { emoji: "🌊", label: "Soča Valley" },
    { emoji: "🌿", label: "Green Country" },
    { emoji: "🏔", label: "Julian Alps" },
    { emoji: "🍷", label: "Wine" },
  ],
  BG: [
    { emoji: "🏔", label: "Rhodope Mountains" },
    { emoji: "🏖", label: "Black Sea" },
    { emoji: "🕌", label: "Rila Monastery" },
    { emoji: "🥗", label: "Cuisine" },
    { emoji: "🌹", label: "Rose Valley" },
  ],
  LT: [
    { emoji: "🏰", label: "Vilnius Old Town" },
    { emoji: "🌲", label: "Curonian Spit" },
    { emoji: "🎶", label: "Song Festival" },
    { emoji: "🏙", label: "Kaunas" },
    { emoji: "🌍", label: "Culture" },
  ],
  LV: [
    { emoji: "🏛", label: "Riga Art Nouveau" },
    { emoji: "🌲", label: "Gauja Valley" },
    { emoji: "🎶", label: "Song Festival" },
    { emoji: "🏖", label: "Jūrmala Beach" },
    { emoji: "🌍", label: "Culture" },
  ],
  EE: [
    { emoji: "🏰", label: "Tallinn Old Town" },
    { emoji: "💻", label: "Digital Society" },
    { emoji: "🌲", label: "Forests & Bogs" },
    { emoji: "🌊", label: "Islands" },
    { emoji: "🎶", label: "Song Festival" },
  ],
  IS: [
    { emoji: "🌋", label: "Volcanoes" },
    { emoji: "🌌", label: "Northern Lights" },
    { emoji: "♨️", label: "Hot Springs" },
    { emoji: "🏔", label: "Glaciers" },
    { emoji: "🐋", label: "Whale Watching" },
  ],
  IE: [
    { emoji: "🍀", label: "Cliffs of Moher" },
    { emoji: "🏰", label: "Castles" },
    { emoji: "🍺", label: "Pubs & Guinness" },
    { emoji: "🎶", label: "Traditional Music" },
    { emoji: "🌿", label: "Green Countryside" },
  ],
  LU: [
    { emoji: "🏰", label: "Luxembourg City" },
    { emoji: "🌲", label: "Ardennes" },
    { emoji: "🇪🇺", label: "EU Hub" },
    { emoji: "🍷", label: "Moselle Wine" },
    { emoji: "🌉", label: "Bridges" },
  ],
};

// ─── Top experience ───────────────────────────────────────────────────────────
export const topExperience: Record<string, string> = {
  IN: "Watch sunrise at the Taj Mahal in Agra",
  US: "Road-trip along Route 66 or hike the Grand Canyon",
  GB: "Stroll through the Tower of London and Westminster",
  FR: "See the Eiffel Tower sparkle at night in Paris",
  DE: "Visit a fairy-tale Bavarian castle like Neuschwanstein",
  JP: "Hike to the Fushimi Inari shrine gates at dawn",
  CN: "Walk the Great Wall at Mutianyu at sunrise",
  AU: "Snorkel the Great Barrier Reef off Cairns",
  BR: "Dance at Rio Carnival or cruise the Amazon River",
  CA: "Watch the Northern Lights over Banff National Park",
  ZA: "Spot the Big Five on a Kruger National Park safari",
  AE: "Ascend the Burj Khalifa for a skyline view at dusk",
  SG: "Watch the nightly Gardens by the Bay light show",
  TH: "Explore the temples of Chiang Mai by tuk-tuk",
  IT: "Toss a coin in the Trevi Fountain and wander Rome",
  ES: "See Gaudí's Sagrada Família at the golden hour",
  MX: "Explore the ancient Mayan ruins of Chichen Itza",
  ID: "Watch sunrise from Mount Batur over Bali's caldera",
  NG: "Experience the energy and cuisine of Lagos Island",
  EG: "Sail down the Nile on a traditional felucca at sunset",
  KE: "Witness the Great Migration in the Maasai Mara",
  TR: "Drift over Cappadocia in a hot-air balloon at sunrise",
  SA: "Explore the ancient rose-red city of AlUla at dusk",
  AR: "Watch a live tango show and taste asado in Buenos Aires",
  PL: "Walk the historic streets of Krakow's Old Town",
  NL: "Cycle through the tulip fields of Keukenhof in bloom",
  SE: "Chase the Northern Lights in Swedish Lapland",
  NO: "Cruise through the dramatic Geirangerfjord",
  NZ: "Cruise Milford Sound and hike the Routeburn Track",
  PT: "Ride Tram 28 through Lisbon's historic Alfama district",
  GR: "Watch the iconic Santorini sunset from Oia",
  CH: "Take the Glacier Express through the Swiss Alps",
  AT: "Attend a classical concert in Vienna's Musikverein",
  BE: "Discover the medieval canals of Bruges on foot",
  DK: "Explore colorful Nyhavn harbour by boat in Copenhagen",
  FI: "Spend a night in a glass igloo under the Northern Lights",
  MY: "Explore Borneo's rainforest for orangutans and pygmy elephants",
  PH: "Island-hop through the breathtaking Bacuit Archipelago",
  VN: "Cruise through the limestone karsts of Ha Long Bay",
  LK: "Climb Sigiriya Rock Fortress at sunrise",
  NP: "Trek to Everest Base Camp through Sherpa villages",
  MV: "Snorkel with manta rays in a turquoise Maldivian lagoon",
  TW: "Explore Jiufen's lantern-lit streets after dark",
  KR: "Witness the cherry blossoms at Gyeongbokgung Palace",
  PE: "Trek the Inca Trail to Machu Picchu at sunrise",
  CO: "Sip coffee on a finca in the Coffee Triangle",
  CL: "Stargaze in the Atacama Desert — the clearest skies on Earth",
  MA: "Get lost in the labyrinthine souks of Marrakech",
  TN: "Watch the sun set over the Sahara from a desert camp",
  GH: "Visit Cape Coast Castle and pay tribute to history",
  ET: "Explore the ancient rock-hewn churches of Lalibela",
  TZ: "Witness the Great Migration on the Serengeti plains",
  UG: "Trek through Bwindi Forest for a gorilla encounter",
  QA: "Explore the Museum of Islamic Art along Doha Corniche",
  KW: "Visit the Grand Mosque and walk through the historic souk",
  BH: "Watch the Formula 1 race under the lights at Bahrain International Circuit",
  OM: "Sleep under the stars in the Wahiba Sands desert",
  JO: "Explore the rose-red Treasury of Petra by candlelight",
  IL: "Walk the Old City of Jerusalem through its four quarters",
  RU: "Admire the onion domes of St. Basil's Cathedral on Red Square",
  UA: "Stroll the cobblestone streets of Lviv's old town",
  CZ: "Walk across the Charles Bridge in misty early-morning Prague",
  HU: "Soak in a thermal bath and watch dusk over the Danube",
  RO: "Drive the Transfăgărășan mountain road through Transylvania",
  HR: "Walk the medieval walls of Dubrovnik at sunset",
  RS: "Dance the night away in a river barge club on the Danube",
  SK: "Hike through the High Tatras to Rysy peak",
  SI: "Row across the glacial Lake Bled at dawn",
  BG: "Visit Rila Monastery nestled in the Rhodope Mountains",
  LT: "Explore the baroque splendour of Vilnius Old Town",
  LV: "Admire Art Nouveau architecture on a stroll through Riga",
  EE: "Walk the medieval walls of Tallinn's Old Town at dusk",
  IS: "Bathe in the Blue Lagoon beneath the midnight sun",
  IE: "Stand on the Cliffs of Moher as the Atlantic swells below",
  LU: "Walk the ramparts of Luxembourg City's UNESCO fortress",
};

// ─── Fallback defaults ────────────────────────────────────────────────────────
export const DEFAULT_VISA: VisaStatus = "required";
export const DEFAULT_BEST_TIME = "Check local conditions";
export const DEFAULT_SAFETY: SafetyLevel = "caution";
export const DEFAULT_CURRENCY_TIP = "Carry some local cash";
export const DEFAULT_KNOWN_FOR: KnownForItem[] = [
  { emoji: "🌍", label: "Culture" },
  { emoji: "🏛", label: "History" },
];
export const DEFAULT_TOP_EXPERIENCE = "Explore the local culture and cuisine";

// ─── Approximate flight time from Delhi (hours, non-stop or best route) ──────
export const flightHoursFromDelhi: Record<string, number> = {
  AE: 3,  TH: 6,  SG: 6,  MY: 7,  LK: 3,  MV: 3,  NP: 2,
  JP: 9,  KR: 9,  CN: 7,  HK: 7,  TW: 7,  VN: 6,  ID: 8,
  PH: 7,  AU: 13, NZ: 17, GB: 9,  FR: 9,  DE: 9,  IT: 9,
  ES: 10, PT: 11, GR: 7,  TR: 6,  RU: 8,  US: 15, CA: 16,
  MX: 17, BR: 18, ZA: 12, KE: 8,  ET: 7,  TZ: 9,  EG: 6,
  MA: 9,  NG: 10, SA: 5,  QA: 4,  KW: 5,  BH: 5,  OM: 4,
  JO: 5,  IL: 6,  PK: 2,  BD: 3,  MM: 4,  KH: 6,  LA: 6,
  NL: 9,  BE: 10, CH: 9,  AT: 9,  SE: 10, NO: 11, DK: 10,
  FI: 10, PL: 8,  CZ: 9,  HU: 8,  RO: 7,  HR: 8,  RS: 8,
  BG: 7,  UA: 7,  BY: 8,  LT: 9,  LV: 9,  EE: 9,  IS: 11,
  IE: 10, LU: 10, SK: 9,  SI: 9,  UZ: 4,  KZ: 6,  GE: 5,
  AM: 5,  AZ: 5,  IR: 4,  IQ: 5,  SY: 5,  LB: 5,  PS: 5,
  PE: 19, CO: 18, CL: 21, AR: 20, VE: 18, BO: 20, EC: 20,
  IN: 0,  // Home
};

// ─── Language tips for Indian travellers ─────────────────────────────────────
export type LanguageTip = "english-wide" | "english-limited" | "hindi-ok" | "local-only";
export const languageTip: Record<string, LanguageTip> = {
  US: "english-wide", GB: "english-wide", AU: "english-wide",
  CA: "english-wide", NZ: "english-wide", SG: "english-wide",
  IE: "english-wide", ZA: "english-wide", NG: "english-wide",
  KE: "english-wide", GH: "english-wide", TZ: "english-wide",
  UG: "english-wide", PH: "english-wide",
  AE: "english-limited", QA: "english-limited", KW: "english-limited",
  BH: "english-limited", SA: "english-limited", OM: "english-limited",
  TH: "english-limited", MY: "english-limited", LK: "english-limited",
  MV: "english-limited", ID: "english-limited", VN: "english-limited",
  EG: "english-limited", MA: "english-limited", TN: "english-limited",
  GR: "english-limited", TR: "english-limited",
  NP: "hindi-ok", // Very similar to Hindi
  JP: "local-only", CN: "local-only", KR: "local-only", RU: "local-only",
  FR: "local-only", DE: "local-only", ES: "local-only", IT: "local-only",
  PT: "local-only", PL: "local-only", CZ: "local-only", HU: "local-only",
  RO: "local-only", HR: "local-only", RS: "local-only",
};

// ─── Popular destinations for Indian passport holders ─────────────────────────
export const popularWithIndians = new Set<string>([
  "AE", "TH", "SG", "MY", "LK", "MV", "NP", "US", "GB", "AU",
  "FR", "DE", "IT", "JP", "ID", "VN", "TR", "KE", "TZ", "ZA",
  "QA", "BH", "OM", "SA", "NZ", "CA", "KR",
]);

// ─── India reference data (for comparison stats) ──────────────────────────────
export const INDIA_GDP_PER_CAPITA_USD = 2601;   // World Bank 2023
export const INDIA_POPULATION = 1_428_627_663;  // 2023

// ─── Multi-home-country visa data ─────────────────────────────────────────────
// Nested: visaByHome[homeCode][destCode] = VisaStatus
// Source: Henley Passport Index / IATA / gov travel advisories (2024)
export const visaByHome: Record<string, Record<string, VisaStatus>> = {
  IN: {
    IN:"free", US:"required", GB:"required", FR:"required", DE:"required",
    JP:"required", CN:"required", AU:"required", BR:"free", CA:"required",
    ZA:"required", AE:"on-arrival", SG:"required", TH:"on-arrival", IT:"required",
    ES:"required", MX:"free", ID:"free", NG:"on-arrival", EG:"on-arrival",
    KE:"e-visa", TR:"e-visa", SA:"e-visa", AR:"free", NL:"required", SE:"required",
    NZ:"e-visa", GR:"required", MY:"free", PH:"free", VN:"e-visa", LK:"e-visa",
    NP:"free", MV:"on-arrival", QA:"on-arrival", KW:"required", BH:"on-arrival",
    OM:"on-arrival", JO:"on-arrival", IL:"required", RU:"required", UA:"free",
    TN:"on-arrival", GH:"on-arrival", ET:"on-arrival", TZ:"on-arrival",
  },
  US: {
    US:"free", IN:"required", GB:"free", FR:"free", DE:"free", JP:"free",
    CN:"required", AU:"free", BR:"free", CA:"free", ZA:"free", AE:"free",
    SG:"free", TH:"free", IT:"free", ES:"free", MX:"free", ID:"free",
    NG:"on-arrival", EG:"on-arrival", KE:"e-visa", TR:"free", SA:"required",
    AR:"free", NL:"free", SE:"free", NZ:"free", GR:"free", MY:"free",
    PH:"free", VN:"e-visa", LK:"e-visa", NP:"on-arrival", MV:"on-arrival",
    QA:"free", KW:"free", BH:"free", OM:"free", JO:"free", IL:"free",
    RU:"required", UA:"free", TN:"free", GH:"free", TZ:"e-visa",
  },
  GB: {
    GB:"free", IN:"required", US:"free", FR:"free", DE:"free", JP:"free",
    CN:"required", AU:"free", BR:"free", CA:"free", ZA:"free", AE:"free",
    SG:"free", TH:"free", IT:"free", ES:"free", MX:"free", ID:"free",
    NG:"on-arrival", EG:"on-arrival", KE:"e-visa", TR:"free", SA:"required",
    AR:"free", NL:"free", SE:"free", NZ:"free", GR:"free", MY:"free",
    PH:"free", VN:"e-visa", LK:"e-visa", NP:"on-arrival", MV:"on-arrival",
    QA:"free", KW:"free", BH:"free", OM:"free", JO:"free", IL:"free",
    RU:"required", UA:"free", TN:"free",
  },
  AU: {
    AU:"free", IN:"required", US:"free", GB:"free", FR:"free", DE:"free",
    JP:"free", CN:"required", BR:"free", CA:"free", ZA:"free", AE:"free",
    SG:"free", TH:"free", IT:"free", ES:"free", MX:"free", ID:"free",
    NG:"on-arrival", EG:"on-arrival", KE:"e-visa", TR:"free", AR:"free",
    NL:"free", SE:"free", NZ:"free", GR:"free", MY:"free", PH:"free",
    VN:"e-visa", LK:"e-visa", NP:"on-arrival", MV:"on-arrival",
    QA:"free", KW:"free", BH:"free", OM:"free", JO:"free", IL:"free",
    RU:"required", UA:"free",
  },
  CA: {
    CA:"free", IN:"required", US:"free", GB:"free", FR:"free", DE:"free",
    JP:"free", CN:"required", AU:"free", BR:"free", ZA:"free", AE:"free",
    SG:"free", TH:"free", IT:"free", ES:"free", MX:"free", ID:"free",
    NG:"on-arrival", EG:"on-arrival", KE:"e-visa", TR:"free", AR:"free",
    NL:"free", SE:"free", NZ:"free", GR:"free", MY:"free", PH:"free",
    VN:"e-visa", LK:"e-visa", NP:"on-arrival", MV:"on-arrival",
    QA:"free", KW:"free", BH:"free", OM:"free", JO:"free",
    RU:"required", UA:"free",
  },
  DE: {
    DE:"free", IN:"required", US:"free", GB:"free", FR:"free", JP:"free",
    CN:"required", AU:"free", BR:"free", CA:"free", ZA:"free", AE:"free",
    SG:"free", TH:"free", IT:"free", ES:"free", MX:"free", ID:"free",
    NG:"on-arrival", EG:"on-arrival", KE:"e-visa", TR:"free", SA:"required",
    AR:"free", NL:"free", SE:"free", NZ:"free", GR:"free", MY:"free",
    PH:"free", VN:"e-visa", LK:"e-visa", NP:"on-arrival", MV:"on-arrival",
    QA:"free", KW:"free", BH:"free", OM:"free", JO:"free", IL:"free",
    RU:"required", UA:"free",
  },
  FR: {
    FR:"free", IN:"required", US:"free", GB:"free", DE:"free", JP:"free",
    CN:"required", AU:"free", BR:"free", CA:"free", ZA:"free", AE:"free",
    SG:"free", TH:"free", IT:"free", ES:"free", MX:"free", ID:"free",
    NG:"on-arrival", EG:"on-arrival", KE:"e-visa", TR:"free", SA:"required",
    AR:"free", NL:"free", SE:"free", NZ:"free", GR:"free", MY:"free",
    PH:"free", VN:"e-visa", LK:"e-visa", NP:"on-arrival", MV:"on-arrival",
    QA:"free", KW:"free", BH:"free", OM:"free", JO:"free",
    RU:"required", UA:"free",
  },
  JP: {
    JP:"free", IN:"required", US:"free", GB:"free", FR:"free", DE:"free",
    CN:"required", AU:"free", BR:"free", CA:"free", ZA:"free", AE:"free",
    SG:"free", TH:"free", IT:"free", ES:"free", MX:"free", ID:"free",
    NG:"on-arrival", EG:"on-arrival", KE:"e-visa", TR:"free", AR:"free",
    NL:"free", SE:"free", NZ:"free", GR:"free", MY:"free", PH:"free",
    VN:"e-visa", LK:"e-visa", NP:"on-arrival", MV:"on-arrival",
    QA:"free", KW:"free", BH:"free", OM:"free", JO:"free", IL:"free",
    RU:"required", UA:"free",
  },
  SG: {
    SG:"free", IN:"required", US:"free", GB:"free", FR:"free", DE:"free",
    JP:"free", CN:"on-arrival", AU:"free", BR:"free", CA:"free", ZA:"free",
    AE:"free", TH:"free", IT:"free", ES:"free", MX:"free", ID:"free",
    NG:"on-arrival", EG:"on-arrival", KE:"e-visa", TR:"free", AR:"free",
    NL:"free", SE:"free", NZ:"free", GR:"free", MY:"free", PH:"free",
    VN:"free", LK:"free", NP:"on-arrival", MV:"on-arrival",
    QA:"free", KW:"free", BH:"free", OM:"free", JO:"free", IL:"free",
    RU:"required", UA:"free",
  },
  AE: {
    AE:"free", IN:"on-arrival", US:"free", GB:"free", FR:"free", DE:"free",
    JP:"free", CN:"free", AU:"free", BR:"free", CA:"free", ZA:"free",
    SG:"free", TH:"free", IT:"free", ES:"free", MX:"free", ID:"free",
    NG:"on-arrival", EG:"free", KE:"e-visa", TR:"free", SA:"free",
    AR:"free", NL:"free", SE:"free", NZ:"free", GR:"free", MY:"free",
    PH:"free", VN:"free", LK:"on-arrival", NP:"on-arrival", MV:"on-arrival",
    QA:"free", KW:"free", BH:"free", OM:"free", JO:"free", IL:"required",
    RU:"required", UA:"free",
  },
};

/** Convenience: get visa status from home → dest, falling back to IN-centric data */
export function getVisaStatus(homeCode: string, destCode: string): VisaStatus {
  return visaByHome[homeCode]?.[destCode]
    ?? visaByHome["IN"]?.[destCode]
    ?? visaForIndian[destCode]
    ?? "required";
}

// ─── Multi-home-country flight hours ──────────────────────────────────────────
// flightHoursByHome[homeCode][destCode] = hours
export const flightHoursByHome: Record<string, Record<string, number>> = {
  IN: {
    AE:3,TH:6,SG:6,MY:7,LK:3,MV:3,NP:2,JP:9,KR:9,CN:7,HK:7,TW:7,VN:6,ID:8,
    PH:7,AU:13,NZ:17,GB:9,FR:9,DE:9,IT:9,ES:10,PT:11,GR:7,TR:6,RU:8,US:15,
    CA:16,MX:17,BR:18,ZA:12,KE:8,ET:7,TZ:9,EG:6,MA:9,NG:10,SA:5,QA:4,KW:5,
    BH:5,OM:4,JO:5,IL:6,PK:2,BD:3,MM:4,KH:6,NL:9,BE:10,CH:9,AT:9,SE:10,
    NO:11,DK:10,FI:10,PL:8,CZ:9,HU:8,RO:7,HR:8,UA:7,UZ:4,GE:5,AM:5,AZ:5,
    IN:0,
  },
  US: {
    GB:8,FR:10,DE:10,IT:11,ES:11,PT:9,GR:13,TR:12,AE:14,SG:19,JP:14,KR:14,
    AU:20,NZ:17,CN:14,TH:18,IN:15,MX:4,CA:5,BR:10,AR:12,ZA:17,KE:15,EG:12,
    MA:10,IL:13,SA:14,QA:14,NG:12,PH:18,VN:18,MY:19,SG:19,HK:16,TW:16,
    GB:8,NL:10,BE:10,SE:10,NO:10,DK:10,FI:11,PL:11,CZ:11,HU:11,RO:12,
    US:0,
  },
  GB: {
    US:8,FR:2,DE:2,IT:3,ES:2,PT:2,GR:4,TR:4,AE:7,SG:14,JP:13,KR:12,AU:21,
    NZ:24,CN:11,TH:12,IN:9,MX:11,CA:9,BR:11,AR:14,ZA:12,KE:9,EG:5,MA:4,
    IL:5,SA:7,QA:6,NG:7,TZ:9,PH:14,VN:12,MY:13,HK:12,TW:13,NL:1,BE:1,
    SE:2,NO:2,DK:2,FI:3,PL:3,CZ:2,HU:3,RO:3,UA:3,
    GB:0,
  },
  AU: {
    NZ:3,ID:6,SG:8,MY:8,TH:9,JP:10,KR:11,CN:11,HK:9,TW:11,PH:9,VN:9,
    IN:13,AE:14,GB:21,US:20,CA:21,FR:22,DE:22,IT:22,ZA:12,KE:14,EG:15,
    QA:14,SA:15,TR:14,GR:15,IL:15,MX:23,BR:21,AR:22,
    AU:0,
  },
  CA: {
    US:3,GB:9,FR:10,DE:10,IT:11,ES:11,MX:5,BR:10,AR:11,JP:13,KR:13,
    CN:13,AU:17,NZ:16,IN:14,AE:14,SG:18,TH:17,KE:14,ZA:16,EG:12,IL:13,
    CA:0,
  },
  DE: {
    US:10,GB:2,FR:2,IT:2,ES:3,PT:3,GR:3,TR:4,AE:7,SG:13,JP:12,KR:12,AU:22,
    NZ:24,CN:10,TH:11,IN:9,MX:12,CA:10,BR:12,AR:14,ZA:12,KE:8,EG:5,MA:4,
    IL:4,SA:7,QA:6,NG:7,TZ:9,NL:1,BE:1,SE:2,NO:2,DK:2,FI:3,PL:2,CZ:1,HU:2,
    DE:0,
  },
  FR: {
    US:10,GB:2,DE:2,IT:2,ES:2,PT:2,GR:3,TR:4,AE:7,SG:13,JP:13,KR:13,AU:23,
    CN:11,TH:12,IN:9,MX:11,CA:9,BR:10,AR:13,ZA:11,KE:8,EG:5,MA:3,
    IL:5,SA:7,QA:6,NG:7,TZ:9,NL:1,BE:1,SE:3,NO:3,DK:3,FI:4,PL:3,CZ:2,
    FR:0,
  },
  JP: {
    US:14,GB:13,FR:13,DE:12,IT:13,AU:10,NZ:11,KR:2,CN:4,SG:7,TH:6,IN:9,
    AE:10,CA:12,MX:15,BR:24,ZA:16,KE:14,EG:12,IL:12,SA:10,QA:10,PH:4,
    VN:5,MY:7,HK:4,TW:3,ID:7,TZ:14,
    JP:0,
  },
  SG: {
    IN:6,MY:1,ID:2,TH:2,VN:3,PH:3,KH:2,AU:8,NZ:11,JP:7,KR:7,CN:5,HK:4,
    TW:5,GB:14,FR:13,DE:13,AE:7,US:19,CA:18,ZA:13,KE:11,AU:8,
    SG:0,
  },
  AE: {
    IN:3,PK:3,BD:4,SG:7,MY:7,TH:7,LK:4,MV:4,JP:10,KR:10,CN:9,AU:14,
    GB:7,FR:7,DE:7,IT:7,ES:8,GR:5,TR:4,EG:3,SA:2,QA:2,KW:2,BH:2,OM:3,
    JO:3,IL:3,KE:6,TZ:7,ZA:10,NG:7,MA:8,US:14,CA:14,NZ:17,
    AE:0,
  },
};

/** Convenience: get flight hours from home → dest */
export function getFlightHours(homeCode: string, destCode: string): number | null {
  return flightHoursByHome[homeCode]?.[destCode]
    ?? (homeCode === "IN" ? flightHoursFromDelhi[destCode] : null)
    ?? null;
}

// ─── Popular destinations by home country ─────────────────────────────────────
export const popularByHome: Record<string, Set<string>> = {
  IN: popularWithIndians,
  US: new Set(["GB","FR","IT","MX","CA","DE","ES","JP","AU","BR","DO","TH","IN","NZ","AE"]),
  GB: new Set(["ES","FR","PT","GR","IT","DE","AU","US","TH","IN","MX","AE","ZA","NZ","JP"]),
  AU: new Set(["ID","TH","US","GB","SG","NZ","JP","FR","IT","ES","DE","MY","VN","MV","AE"]),
  CA: new Set(["US","GB","FR","MX","IT","DE","AU","JP","ES","TH","NZ","IN","AE","CR","CU"]),
  DE: new Set(["ES","IT","TR","GR","AT","FR","HR","US","PT","TH","CN","AE","JP","NL","CZ"]),
  FR: new Set(["ES","IT","PT","GR","US","GB","MA","TH","SB","DE","JP","AU","AE","MX","MU"]),
  JP: new Set(["TH","TW","KR","HK","SG","VN","AU","US","HI","FR","IT","GB","DE","AE","ID"]),
  SG: new Set(["MY","JP","AU","TH","KR","UK","ID","TW","VN","HK","FR","IT","US","NZ","MV"]),
  AE: new Set(["IN","GB","US","TH","MY","ID","TZ","KE","ZA","QA","BH","OM","SA","EG","TR"]),
};

/** Convenience: is destCode popular from homeCode's perspective? */
export function isPopularFrom(homeCode: string, destCode: string): boolean {
  return (popularByHome[homeCode] ?? popularWithIndians).has(destCode);
}

// ─── Home country reference GDP and population data ───────────────────────────
export const homeCountryData: Record<string, { gdpPerCapita: number; population: number; name: string; hub: string }> = {
  IN: { gdpPerCapita: 2601,   population: 1_428_627_663, name: "India",          hub: "Delhi" },
  US: { gdpPerCapita: 80_035, population: 335_893_238,   name: "United States",  hub: "New York" },
  GB: { gdpPerCapita: 48_912, population: 67_596_281,    name: "United Kingdom", hub: "London" },
  AU: { gdpPerCapita: 64_964, population: 26_439_111,    name: "Australia",      hub: "Sydney" },
  CA: { gdpPerCapita: 52_722, population: 38_781_292,    name: "Canada",         hub: "Toronto" },
  DE: { gdpPerCapita: 51_203, population: 83_294_633,    name: "Germany",        hub: "Frankfurt" },
  FR: { gdpPerCapita: 44_408, population: 68_170_228,    name: "France",         hub: "Paris" },
  JP: { gdpPerCapita: 33_950, population: 123_294_513,   name: "Japan",          hub: "Tokyo" },
  SG: { gdpPerCapita: 88_447, population: 5_917_648,     name: "Singapore",      hub: "Singapore" },
  AE: { gdpPerCapita: 48_952, population: 9_441_429,     name: "UAE",            hub: "Dubai" },
};
